// isai.js - Compact with two base URLs and durations
const repos = [
  {
    base: "https://github.com/atsuperman/play2/raw/main/",
    songs: [
{ file: "O Podu.m4a", details: "🎬 Gemini (2002) / 🎙️ S. P. Balasubrahmanyam, Anuradha Sriram / 🎼 Bharadwaj / 📝 Vairamuthu", duration: 240 },
{ file: "Deewana Deewana.m4a", details: "🎬 Gemini (2002) / 🎙️ Sadhana Sargam / 🎼 Bharadwaj / 📝 Vairamuthu", duration: 266 },
{ file: "Aura 10 10.m4a", details: "🎬 Meesaya Murukku 2 (2026) / 🎙️ Hiphop Tamizha, Thamizh Aadhavan / 🎼 Hiphop Tamizha / 📝 Hiphop Tamizha, Thamizh Aadhavan", duration: 129 },
{ file: "Great Ji.m4a", details: "🎬 Meesaya Murukku (2017) / 🎙️ Hiphop Tamizha / 🎼 Hiphop Tamizha / 📝 Hiphop Tamizha", duration: 262 },
{ file: "Enna Nadanthalum.m4a", details: "🎬 Meesaya Murukku (2017) / 🎙️ Kaushik Krish, Hiphop Tamizha / 🎼 Hiphop Tamizha / 📝 Hiphop Tamizha", duration: 245 },
{ file: "Maatikichu.m4a", details: "🎬 Meesaya Murukku (2017) / 🎙️ Mahalingam, Hiphop Tamizha / 🎼 Hiphop Tamizha / 📝 Hiphop Tamizha", duration: 198 },
{ file: "Pavazha Malli.m4a", details: "📀 Pavazha Malli (2026) / 🎙️ Sai Abhyankkar, Shruti Haasan / 🎼 Sai Abhyankkar", duration: 253 },
{ file: "Vetri Vetri Endru sollum.m4a", details: "🎬 Kattumarakaran (1995) / 🎙️ S. P. Balasubrahmanyam, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 331 },
{ file: "Vacha Parvai Theerathadi.m4a", details: "🎬 Ilamai Kolam (1980) / 🎙️ K. J. Yesudas / 🎼 Ilaiyaraaja / 📝 Gangai Amaran", duration: 234 },  
{ file: "Chikkimukki Kallu.m4a", details: "🎬 Citizen (2001) / 🎙️ Shankar Mahadevan, Sadhana Sargam / 🎼 Deva / 📝 Vairamuthu", duration: 411 },
{ file: "I Like You.m4a", details: "🎬 Citizen (2001) / 🎙️ Vasundhara Das / 🎼 Deva / 📝 Vairamuthu", duration: 412 },
{ file: "Merkey Vidhaitha.m4a", details: "🎬 Citizen (2001) / 🎙️ Shankar Mahadevan / 🎼 Deva / 📝 Vairamuthu", duration: 373 },
{ file: "Pookkara.m4a", details: "🎬 Citizen (2001) / 🎙️ Shankar Mahadevan, Vasundhara Das / 🎼 Deva / 📝 Vairamuthu", duration: 380 },
{ file: "Haiyo Paththikichu.m4a", details: "🎬 Rhythm (2000) / 🎙️ Udit Narayan, Vasundhara Das / 🎼 A R Rahman / 📝 Vairamuthu", duration: 319 },
{ file: "Kaattrae En.m4a", details: "🎬 Rhythm (2000) / 🎙️ Unni Krishnan, Kavitha Paudwal / 🎼 A R Rahman / 📝 Vairamuthu", duration: 380 },
{ file: "Nathiyae.m4a", details: "🎬 Rhythm (2000) / 🎙️ Unni Menon / 🎼 A R Rahman / 📝 Vairamuthu", duration: 414 },
{ file: "Thaniye thannanthaniye.m4a", details: "🎬 Rhythm (2000) / 🎙️ Shankar Mahadevan / 🎼 A R Rahman / 📝 Vairamuthu", duration: 326 },
{ file: "Vilakkethu.m4a", details: "🎬 Per Sollum Pillai (1987) / 🎙️ Malaysia Vasudevan / 🎼 Ilaiyaraaja / 📝 Gangai Amaran", duration: 273 },
{ file: "Adi Kaana karum.m4a", details: "🎬 Poonthotta Kavalkaran (1988) / 🎙️ K J Yesudas / 🎼 Ilaiyaraaja / 📝 Gangai Amaran", duration: 309 },
{ file: "Paadatha Themmaangu.m4a", details: "🎬 Poonthotta Kavalkaran (1988) / 🎙️ S P Balasubrahmanyam / 🎼 Ilaiyaraaja / 📝 Gangai Amaran", duration: 284 },
{ file: "Paaramal Paartha.m4a", details: "🎬 Poonthotta Kavalkaran (1988) / 🎙️ Mano, K S Chithra / 🎼 Ilaiyaraaja / 📝 Gangai Amaran", duration: 266 },
{ file: "Sindhiya Venmani.m4a", details: "🎬 Poonthotta Kaavalkaaran (1988) / 🎙️ K J Yesudas, P Susheela / 🎼 Ilaiyaraaja / 📝 Gangai Amaran", duration: 263 },
{ file: "Nee Pogum.m4a", details: "🎬 Gramathu Minnal (1987) / 🎙️ Malaysia Vasudevan, K S Chithra / 🎼 Ilaiyaraaja / 📝 Gangai Amaran", duration: 282 },
{ file: "Rettaikili sutthi.m4a", details: "🎬 Gramathu Minnal (1987) / 🎙️ Ilaiyaraaja, K S Chithra / 🎼 Ilaiyaraaja / 📝 Gangai Amaran", duration: 305 },
{ file: "Kandaa Vara Sollunga.m4a", details: "🎬 Karnan (2021) / 🎙️ Kidakkuzhi Mariyammal, Santhosh Narayanan / 🎼 Santhosh Narayanan / 📝 Mari Selvaraj", duration: 286 },
{ file: "Uttradheenga.m4a", details: "🎬 Karnan (2021) / 🎙️ Dhee, Santhosh Narayanan / 🎼 Santhosh Narayanan / 📝 Mari Selvaraj", duration: 289 },
{ file: "Ill Be There For You.m4a", details: "📀 Ill Be There For You (From Sweetheart) (2025) / 🎙️ Yuvan Shankar Raja / 🎼 Yuvan Shankar Raja / 📝 Na Muthukumar", duration: 206 },
{ file: "Onappu Thattu.m4a", details: "🎬 Chinna Jameen (1993) / 🎙️ Ilaiyaraaja, Swarnalatha / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 303 },
{ file: "Oru Matharappu.m4a", details: "🎬 Chinna Jameen (1993) / 🎙️ Mano, K S Chithra / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 282 },
{ file: "Chinna Kili.m4a", details: "🎬 Chinna Gounder (1992) / 🎙️ S P Balasubrahmanyam, S Janaki / 🎼 Ilaiyaraaja / 📝 R V Udhaya Kumar", duration: 126 },
{ file: "Koondu Kulla.m4a", details: "🎬 Chinna Gounder (1992) / 🎙️ S P Balasubrahmanyam, S Janaki / 🎼 Ilaiyaraaja / 📝 R V Udhaya Kumar", duration: 257 },
{ file: "Muthumani Malai.m4a", details: "🎬 Chinna Gounder (1992) / 🎙️ S P Balasubrahmanyam, P Susheela / 🎼 Ilaiyaraaja / 📝 R V Udhaya Kumar", duration: 299 },
{ file: "Vaadi Machiniye.m4a", details: "🎬 Parthiban Kanavu (2003) / 🎙️ Sirkazhi Sivachidambaram, Malathy Lakshman / 🎼 Vidyasagar / 📝 Arivumathi", duration: 277 },
{ file: "O Butterfly Duet.m4a", details: "🎬 Meera (1992) / 🎙️ S P Balasubrahmanyam, Asha Bhosle / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 346 },
{ file: "Pudhu Routeladan.m4a", details: "🎬 Meera (1992) / 🎙️ K J Yesudas, K S Chithra / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 300 },
{ file: "Iyera Meenu.m4a", details: "🎬 Mappillai Gounder (1997) / 🎙️ Swarnalatha, Mano / 🎼 Deva / 📝 Kalidasan", duration: 242 },
{ file: "Moonu Mozham.m4a", details: "🎬 Senathipathi (1996) / 🎙️ S P Balasubrahmanyam, K S Chithra / 🎼 Deva / 📝 Vairamuthu", duration: 278 },
{ file: "Unnaikaanamal.m4a", details: "🎬 Kavithai Paadum Alaigal (1990) / 🎙️ Arunmozhi, K S Chithra / 🎼 Ilaiyaraaja / 📝 Gangai Amaran", duration: 309 },
{ file: "Kanne En.m4a", details: "🎬 Kavithai Paadum Alaigal (1990) / 🎙️ Mano, K S Chithra / 🎼 Ilaiyaraaja / 📝 Gangai Amaran", duration: 296 },
{ file: "Vaanilaa Thenilaa.m4a", details: "🎬 Kavithai Paadum Alaigal (1990) / 🎙️ Mano, K S Chithra / 🎼 Ilaiyaraaja / 📝 Gangai Amaran", duration: 271 },
{ file: "Anbe nee mayila.m4a", details: "🎬 Ninavirukkum Varai (1999) / 🎙️ Unni Menon, Sujatha Mohan / 🎼 Deva / 📝 Pazhani Bharathi", duration: 325 },
{ file: "KathAdikkuthu kathu.m4a", details: "🎬 Ninaivirukkum Varai (1999) / 🎙️ Sabesh, Krishnaraj / 🎼 Deva / 📝 K Subash", duration: 258 },
{ file: "Thirupathi Elumalai.m4a", details: "🎬 Ninaivirukkum Varai (1999) / 🎙️ Mano, Krishnaraj, Deva / 🎼 Deva / 📝 K Subash", duration: 328 },
{ file: "A For Ambica.m4a", details: "🎬 Naan Pesa Ninaipathellam (1993) / 🎙️ Mano, Deepan Chakravarthi, Swarnalatha / 🎼 Sirpy / 📝 Poovarasu", duration: 232 },
{ file: "Alelankiliye Duet.m4a", details: "🎬 Naan Pesa Ninaipathellam (1993) / 🎙️ Mano, P Susheela / 🎼 Sirpy / 📝 Palani Bharathi", duration: 255 },
{ file: "Alelankiliye Solo.m4a", details: "🎬 Naan Pesa Ninaipathellam (1993) / 🎙️ K J Yesudas / 🎼 Sirpy / 📝 Palani Bharathi", duration: 250 },
{ file: "Kaverikku.m4a", details: "🎬 Naan Pesa Ninaipathellam (1993) / 🎙️ Mano / 🎼 Sirpy / 📝 Palani Bharathi", duration: 159 },
{ file: "Manodudhu.m4a", details: "🎬 Naan Pesa Ninaipathellam (1993) / 🎙️ K S Chithra / 🎼 Sirpy / 📝 Palani Bharathi", duration: 97 },
{ file: "Poonguyil Ragame.m4a", details: "🎬 Naan Pesa Ninaipathellam (1993) / 🎙️ S P Balasubrahmanyam / 🎼 Sirpy / 📝 Palani Bharathi", duration: 233 },
{ file: "Jinguchaa.m4a", details: "🎬 Thug Life (2025) / 🎙️ Vaishali Samant, Shakthisree Gopalan, Adithya RK / 🎼 A. R. Rahman / 📝 Kamal Haasan", duration: 260 },
{ file: "Muththa Mazhai -Chinmayi.m4a", details: "🎬 Thug Life (2025) / 🎙️ Chinmayi Sripaada / 🎼 A R Rahman / 📝 Siva Ananth", duration: 240 },
{ file: "Muththa Mazhai- Dhee.m4a", details: "🎬 Thug Life (2025) / 🎙️ Dhee, Siva Ananth / 🎼 A R Rahman / 📝 Siva Ananth", duration: 241 },
{ file: "Aararoo.m4a", details: "🎬 Veera Thalattu (1998) / 🎙️ Swarnalatha / 🎼 Ilaiyaraaja / 📝 Kasthuri Raja", duration: 314 },
{ file: "Amman kovil.m4a", details: "🎬 Veera Thalattu (1998) / 🎙️ Gangai Amaran, S. P. Sailaja / 🎼 Ilaiyaraaja / 📝 Kasthuri Raja", duration: 393 },
{ file: "Kadha Pola.m4a", details: "🎬 Veera Thalattu (1998) / 🎙️ Ilaiyaraaja / 🎼 Ilaiyaraaja / 📝 Kasthuri Raja", duration: 314 },
{ file: "Kiliyai Pole.m4a", details: "🎬 Veera Thalattu (1998) / 🎙️ Gangai Amaran, S. P. Sailaja / 🎼 Ilaiyaraaja / 📝 Kasthuri Raja", duration: 170 },
{ file: "Kumbabhishekam.m4a", details: "🎬 Veera Thalattu (1998) / 🎙️ S P Balasubrahmanyam, K S Chithra / 🎼 Ilaiyaraaja / 📝 Kasthuri Raja", duration: 312 },
{ file: "Patta Pagal.m4a", details: "🎬 Veera Thalattu (1998) / 🎙️ Malaysia Vasudevan, Swarnalatha / 🎼 Ilaiyaraaja / 📝 Kasthuri Raja", duration: 173 },
{ file: "Santhu Pottu.m4a", details: "🎬 Veera Thalattu (1998) / 🎙️ Arunmozhi, Swarnalatha / 🎼 Ilaiyaraaja / 📝 Kasthuri Raja", duration: 297 },
{ file: "Vadi Patti.m4a", details: "🎬 Veera Thalattu (1998) / 🎙️ Gangai Amaran, S. P. Sailaja / 🎼 Ilaiyaraaja / 📝 Kasthuri Raja", duration: 296 },
{ file: "Ezhumalaiyaney.m4a", details: "🎬 Thayumanavan (2003) / 🎙️ Manikka Vinayagam, Female Vocalist (Uncredited) / 🎼 Vaigundavasaan / 📝 Vaigundavasaan, Saravanan", duration: 344 },
{ file: "Karu Karu Karupayi.m4a", details: "🎬 Eazhaiyin Sirippil (2000) / 🎙️ Unni Menon, Anuradha Sriram / 🎼 Deva / 📝 K. Subash", duration: 314 },
{ file: "Pachai Kallu.m4a", details: "🎬 Eazhaiyin Sirippil (2000) / 🎙️ Mano, Swarnalatha / 🎼 Deva / 📝 K. Subash", duration: 343 },
{ file: "Purave En Pt 1.m4a", details: "🎬 Eazhaiyin Sirippil (2000) / 🎙️ Deva, Hariharan, Sujatha Mohan / 🎼 Deva / 📝 Palani Bharathi", duration: 340 },
{ file: "Purave En Pt 2.m4a", details: "🎬 Eazhaiyin Sirippil (2000) / 🎙️ Deva, Unni Menon, Sujatha Mohan / 🎼 Deva / 📝 Palani Bharathi", duration: 343 },
{ file: "Sakkaravalli.m4a", details: "🎬 Eazhaiyin Sirippil (2000) / 🎙️ Unni Menon / 🎼 Deva / 📝 Na. Muthukumar", duration: 293 },
{ file: "Yeppa Yeppa.m4a", details: "🎬 Eazhaiyin Sirippil (2000) / 🎙️ Mano, Krishnaraj, Prabhu Deva, Vivek, K. Subash / 🎼 Deva / 📝 K. Subash", duration: 305 },
{ file: "Mayil Pola.m4a", details: "🎬 Bharathi (2000) / 🎙️ Bhavatharini / 🎼 Ilaiyaraaja / 📝 Mu. Metha", duration: 272 },
{ file: "Kona Kondakari.m4a", details: "🎬 Madha Yaanai Koottam (2013) / 🎙️ G. V. Prakash Kumar / 🎼 N. R. Raghunanthan / 📝 Yegathasi", duration: 274 },
{ file: "Ooru Oram.m4a", details: "🎬 Thaai Manasu (1994) / 🎙️ S. P. Balasubrahmanyam, S. Janaki / 🎼 Deva / 📝 Kasthuri Raja", duration: 296 },
{ file: "Thoothuvelayela.m4a", details: "🎬 Thaai Manasu (1994) / 🎙️ Mano, S. Janaki / 🎼 Deva / 📝 Kasthuri Raja", duration: 280 },
{ file: "Thuppakinna.m4a", details: "🎬 Thaai Manasu (1994) / 🎙️ S. Janaki / 🎼 Deva / 📝 Kasthuri Raja", duration: 262 },
{ file: "Kambi Mathappu.m4a", details: "🎬 Sevarkkodi (2012) / 🎙️ M. L. R. Karthikeyan / 🎼 C. Sathya / 📝 Vairamuthu", duration: 240 },
{ file: "Vethala Madichu.m4a", details: "🎬 Mannukketha Ponnu (1985) / 🎙️ Gangai Amaran, S. P. Sailaja / 🎼 Gangai Amaran", duration: 309 },
{ file: "Antha Nilava Thaan.m4a", details: "🎬 Muthal Mariyathai (1985) / 🎙️ Ilaiyaraaja, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Vairamuthu", duration: 272 },
{ file: "Eratha Malai Mele.m4a", details: "🎬 Muthal Mariyathai (1985) / 🎙️ Malaysia Vasudevan, S. Janaki / 🎼 Ilaiyaraaja / 📝 Vairamuthu", duration: 126 },
{ file: "Hey Kiliyirukku.m4a", details: "🎬 Muthal Mariyathai (1985) / 🎙️ Ilaiyaraaja, Chorus / 🎼 Ilaiyaraaja / 📝 Vairamuthu", duration: 68 },
{ file: "Poongatru Thirumbuma.m4a", details: "🎬 Muthal Mariyathai (1985) / 🎙️ Malaysia Vasudevan, S. Janaki / 🎼 Ilaiyaraaja / 📝 Vairamuthu", duration: 262 },
{ file: "Raasave Unna Nambi.m4a", details: "🎬 Muthal Mariyathai (1985) / 🎙️ S. Janaki / 🎼 Ilaiyaraaja / 📝 Vairamuthu", duration: 272 },
{ file: "Vetti Veru Vasam.m4a", details: "🎬 Muthal Mariyathai (1985) / 🎙️ Malaysia Vasudevan, S. Janaki / 🎼 Ilaiyaraaja / 📝 Vairamuthu", duration: 266 },
{ file: "Yeh Kuruvi.m4a", details: "🎬 Muthal Mariyathai (1985) / 🎙️ Malaysia Vasudevan, S. Janaki / 🎼 Ilaiyaraaja / 📝 Vairamuthu", duration: 74 },
{ file: "Vayakkadu.m4a", details: "🎬 Parambarai (1996) / 🎙️ Mano, K. S. Chithra / 🎼 Deva / 📝 Kalidasan", duration: 310 },
{ file: "Chillunu Kaaththu.m4a", details: "🎬 Looty (2001) / 🎙️ Mano, Swarnalatha / 🎼 Deva / 📝 Vaali", duration: 331 },
{ file: "Madurakkara Vivekku.m4a", details: "🎬 Looty (2001) / 🎙️ Vadivelu, Sabesh / 🎼 Deva / 📝 Vaali", duration: 265 },
{ file: "Missu Missu Pappa.m4a", details: "🎬 Looty (2001) / 🎙️ Krishnaraj, Anuradha Sriram / 🎼 Deva / 📝 Vaali", duration: 324 },
{ file: "Velu Vadivelu.m4a", details: "🎬 Looty (2001) / 🎙️ Deva / 🎼 Deva / 📝 Vaali", duration: 344 },
{ file: "Aadiyae Attam Enna.m4a", details: "🎬 En Purusan Kuzhandhai Maadhiri (2001) / 🎙️ Deva / 🎼 Deva / 📝 Kalaikumar", duration: 311 },
{ file: "Chitraiyae Adi.m4a", details: "🎬 En Purushan Kuzhandhai Maadhiri (2001) / 🎙️ Hariharan, Anuradha Sriram / 🎼 Deva / 📝 Kamakodiyan", duration: 343 },
{ file: "Naladi Aaru Angulam.m4a", details: "🎬 En Purushan Kuzhandhai Maadhiri (2001) / 🎙️ Vadivelu / 🎼 Deva / 📝 Karupur Ramu", duration: 288 },
{ file: "Pattaam Poochi Podavai.m4a", details: "🎬 En Purushan Kuzhandhai Maadhiri (2001) / 🎙️ Mano, Anuradha Sriram / 🎼 Deva / 📝 Kalaikumar", duration: 303 },
{ file: "Valavaikum Janangkaluku.m4a", details: "🎬 En Purushan Kuzhandhai Maadhiri (2001) / 🎙️ Sabesh, Krishna Raj / 🎼 Deva / 📝 S. P. Rajkumar", duration: 281 },
{ file: "Oorukulla Unnaiyum.m4a", details: "🎬 Ninaivu Chinnam (1989) / 🎙️ K. S. Chithra, Malaysia Vasudevan / 🎼 Ilaiyaraaja / 📝 Gangai Amaran", duration: 310 },
{ file: "Vaikasi Maasthula.m4a", details: "🎬 Ninaivu Chinnam (1989) / 🎙️ S. P. Balasubrahmanyam, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Gangai Amaran", duration: 276 },
{ file: "Adi Ammaadi.m4a", details: "🎬 Kanni Paruvathile (1979) / 🎙️ S. Janaki / 🎼 Shankar–Ganesh / 📝 Pulamaipithan", duration: 335 },
{ file: "Pattu Vanna-F.m4a", details: "🎬 Kanni Paruvathile (1979) / 🎙️ S. Janaki / 🎼 Shankar–Ganesh / 📝 Pulamaipithan", duration: 288 },
{ file: "Pattu Vanna-M.m4a", details: "🎬 Kanni Paruvathile (1979) / 🎙️ Malaysia Vasudevan / 🎼 Shankar–Ganesh / 📝 Pulamaipithan", duration: 286 },
{ file: "Koottam Nalla.m4a", details: "🎬 Manu Needhi (2000) / 🎙️ Seerkazhi G. Sivachidambaram, Anuradha Sriram / 🎼 Deva / 📝 Lakshmi Priyan", duration: 270 },
{ file: "Mayiladum Parai.m4a", details: "🎬 Manu Needhi (2000) / 🎙️ S. Sathya / 🎼 Deva / 📝 Kalaikumar", duration: 286 },
{ file: "Oru Rojathottam.m4a", details: "🎬 Manu Needhi (2000) / 🎙️ P. Unnikrishnan, K. S. Chithra / 🎼 Deva / 📝 Snehan", duration: 325 },
{ file: "Yele Karuthamma.m4a", details: "🎬 Manu Needhi (2000) / 🎙️ Krishnaraj, Anuradha Sriram / 🎼 Deva / 📝 Snehan", duration: 341 },
{ file: "Bombay City.m4a", details: "🎬 Rasigan (1994) / 🎙️ Vijay, K. S. Chithra / 🎼 Deva / 📝 Vaali", duration: 296 },
{ file: "Jillena Jillena.m4a", details: "🎬 Rasigan (1994) / 🎙️ S. N. Surendar, Swarnalatha / 🎼 Deva / 📝 Vaali", duration: 286 },
{ file: "Aayiram Kodi.m4a", details: "🎬 Karisakattu Poove (2000) / 🎙️ Hariharan / 🎼 Ilaiyaraaja / 📝 Kasthuri Raja", duration: 291 },
{ file: "Ethana Manikku.m4a", details: "🎬 Karisakattu Poove (2000) / 🎙️ Arunmozhi, Anuradha Sriram / 🎼 Ilaiyaraaja / 📝 Kasthuri Raja", duration: 289 },
{ file: "Kuchanooru.m4a", details: "🎬 Karisakattu Poove (2000) / 🎙️ Pushpavanam Kuppusamy, Anitha Kuppusamy / 🎼 Ilaiyaraaja / 📝 Kasthuri Raja", duration: 288 },
{ file: "Mamarathule.m4a", details: "🎬 Karisakattu Poove (2000) / 🎙️ P. Unnikrishnan, Bhavatharini / 🎼 Ilaiyaraaja / 📝 Kasthuri Raja", duration: 305 },
{ file: "Manasirukka.m4a", details: "🎬 Karisakattu Poove (2000) / 🎙️ Pushpavanam Kuppusamy, Swarnalatha / 🎼 Ilaiyaraaja / 📝 Kasthuri Raja", duration: 317 },
{ file: "Un Kendakkalu.m4a", details: "🎬 Karisakattu Poove (2000) / 🎙️ Mano, Swarnalatha / 🎼 Ilaiyaraaja / 📝 Kasthuri Raja", duration: 283 },
{ file: "Elumicham Pazham.m4a", details: "🎬 Killadi Mappillai (1994) / 🎙️ Krishnaraj, Sindhu / 🎼 Deva / 📝 Vaali", duration: 315 },
{ file: "Tajmahal Oviya Kadhal.m4a", details: "🎬 Kalvanin Kadhali (2006) / 🎙️ Vijay Yesudas, Srimathumitha / 🎼 Yuvan Shankar Raja / 📝 Vaali", duration: 306 },
{ file: "Mudhalil Yennai.m4a", details: "🎬 Thalaivaa / 🎙️ S. P. Balasubrahmanyam, K. S. Chithra", duration: 275 },
{ file: "Metti Metti.m4a", details: "🎬 Pullakuttikaran (1995) / 🎙️ S. Janaki, Arunmozhi, Parthiban / 🎼 Deva / 📝 Vairamuthu", duration: 304 },
{ file: "Eettupatti Rasa.m4a", details: "🎬 Ettupatti Rasa (1997) / 🎙️ Napoleon, Swarnalatha / 🎼 Deva / 📝 Kasthuri Raja", duration: 214 },
{ file: "Kathadikuthu.m4a", details: "🎬 Ettupatti Rasa (1997) / 🎙️ Malaysia Vasudevan, S. Janaki / 🎼 Deva / 📝 Kasthuri Raja", duration: 311 },
{ file: "Merku Seemailaa.m4a", details: "🎬 Ettupatti Rasa (1997) / 🎙️ Deva, Swarnalatha / 🎼 Deva / 📝 Kasthuri Raja", duration: 323 },
{ file: "Panju Mittai.m4a", details: "🎬 Ettupatti Rasa (1997) / 🎙️ Malaysia Vasudevan, S. Janaki / 🎼 Deva / 📝 Kasthuri Raja", duration: 297 },
{ file: "Mehangal Ennathottu.m4a", details: "🎬 Amarkalam (1999) / 🎙️ S. P. Balasubrahmanyam / 🎼 Bharadwaj / 📝 Vairamuthu", duration: 344 },
{ file: "Satham Illatha.m4a", details: "🎬 Amarkalam (1999) / 🎙️ S. P. Balasubrahmanyam, Sujatha Mohan / 🎼 Bharadwaj / 📝 Vairamuthu", duration: 259 },
{ file: "Sontha Kuralil Paada.m4a", details: "🎬 Amarkalam (1999) / 🎙️ Shalini / 🎼 Bharadwaj / 📝 Vairamuthu", duration: 299 },
{ file: "Unnodu Vazhatha.m4a", details: "🎬 Amarkalam (1999) / 🎙️ K. S. Chithra / 🎼 Bharadwaj / 📝 Vairamuthu", duration: 319 },
{ file: "Idam Tharuvaya.m4a", details: "🎬 Appu (2000) / 🎙️ P. Unnikrishnan, Pop Shalini / 🎼 Deva / 📝 Vairamuthu", duration: 309 },
{ file: "Yeno Yeno.m4a", details: "🎬 Appu (2000) / 🎙️ Hariharan, Sujatha Mohan, Harini / 🎼 Deva / 📝 Vairamuthu", duration: 370 },
{ file: "Kadalainna Kadalai.m4a", details: "🎬 Pirappu (2007) / 🎙️ Manickka Vinayagam, Anuradha Sriram / 🎼 Bharadwaj / 📝 Kamakodiyan", duration: 313 },
{ file: "En Manathai.m4a", details: "🎬 Kalloori Vaasal (1996) / 🎙️ Hariharan, Anuradha Sriram / 🎼 Deva / 📝 Vaali", duration: 320 },
{ file: "Nilagiri.m4a", details: "🎬 Kalloori Vaasal (1996) / 🎙️ Mano, Swarnalatha / 🎼 Deva / 📝 Vaali", duration: 259 },
{ file: "Poove Nee Aada Vaa.m4a", details: "🎬 Kalki (1996) / 🎙️ Sujatha Mohan / 🎼 Deva / 📝 Ilandevan", duration: 304 },
{ file: "Singapore Selai.m4a", details: "🎬 Kalki (1996) / 🎙️ Mano / 🎼 Deva / 📝 Ilandevan", duration: 291 },
{ file: "Yeazhudhkiren Oru Kadidham.m4a", details: "🎬 Kalki (1996) / 🎙️ K. S. Chithra, Anuradha Sriram / 🎼 Deva / 📝 Ilandevan", duration: 374 },
{ file: "Mamara Anile.m4a", details: "🎬 Dharma Chakkaram (1997) / 🎙️ Sujatha Mohan / 🎼 Deva / 📝 R. V. Udayakumar", duration: 328 },
{ file: "Putta Putta.m4a", details: "🎬 Dharma Chakkaram (1997) / 🎙️ K. S. Chithra, Deva, Krishnaraj / 🎼 Deva / 📝 R. V. Udayakumar", duration: 270 },
{ file: "Sollaikulla Kaatukulla.m4a", details: "🎬 Dharma Chakkaram (1997) / 🎙️ S. P. Balasubrahmanyam, Sujatha / 🎼 Deva / 📝 R. V. Udayakumar", duration: 330 },
{ file: "Kaatradikkum Neram.m4a", details: "🎬 Vivasaayi Magan (1997) / 🎙️ Mano, K. S. Chithra / 🎼 Sirpy / 📝 Palani Bharathi", duration: 278 },
{ file: "Vettaveli Pottalilae.m4a", details: "🎬 Vivasaayi Magan (1997) / 🎙️ Mano, K. S. Chithra / 🎼 Sirpy / 📝 Palani Bharathi", duration: 249 },
{ file: "Ada Da Da Da.m4a", details: "🎬 Arai En 305-il Kadavul (2008) / 🎙️ Santhanam, Ganja Karuppu, Vineeth Sreenivasan, Jayamoorthy / 🎼 Vidyasagar / 📝 Pa. Vijay", duration: 281 },
{ file: "Chori Chori.m4a", details: "🎬 Maaman Magal (1995) / 🎙️ K. S. Chithra, Gurdas Maan / 🎼 Adithyan / 📝 Vaali", duration: 318 },
{ file: "Dhemthana Thomthana.m4a", details: "🎬 Maaman Magal (1995) / 🎙️ Mano, K. S. Chithra / 🎼 Adithyan / 📝 Kalidasan", duration: 222 },
{ file: "kuyile kuyile .m4a", details: "🎬 Maaman Magal (1995) / 🎙️ Sujatha Mohan / 🎼 Adithyan / 📝 Kalidasan", duration: 109 },
{ file: "Cheran chozha Pandiyar.m4a", details: "🎬 Namma Annachi (1994) / 🎙️ S. P. Balasubrahmanyam, S. Janaki / 🎼 Deva / 📝 Vaali", duration: 240 },
{ file: "Enna Dappa Partyinnu.m4a", details: "🎬 Namma Annachi (1994) / 🎙️ S. P. Balasubrahmanyam, K. S. Chithra / 🎼 Deva / 📝 Kalidasan", duration: 240 },
{ file: "Neelagiri Mala Orathila.m4a", details: "🎬 Namma Annachi (1994) / 🎙️ S. P. Balasubrahmanyam, K. S. Chithra / 🎼 Deva / 📝 Vaali", duration: 240 },
{ file: "Mayanginen Solla Thayanginen.m4a", details: "🎬 Naane Raja Naane Mandhiri (1985) / 🎙️ P. Jayachandran, P. Susheela / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 256 },
{ file: "Thegam Siragadikkum.m4a", details: "🎬 Naane Raja Naane Mandhiri (1985) / 🎙️ P. Jayachandran, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Mu. Metha", duration: 274 },
{ file: "Maamara Kuilea.m4a", details: "🎬 En Aasai Rasave (1998) / 🎙️ S. P. Balasubrahmanyam, Swarnalatha / 🎼 Deva / 📝 Kasthuri Raja", duration: 299 },
{ file: "Mayangaadha.m4a", details: "🎬 En Aasai Rasave (1998) / 🎙️ Malaysia Vasudevan, Devi / 🎼 Deva / 📝 Kasthuri Raja", duration: 236 },
{ file: "Mundhi Mundhi Vinaayaganea.m4a", details: "🎬 En Aasai Rasave (1998) / 🎙️ Malaysia Vasudevan, Anuradha Sriram / 🎼 Deva / 📝 Kasthuri Raja", duration: 327 },
{ file: "Pathu Roopa Ravikai Thuni.m4a", details: "🎬 En Aasai Rasave (1998) / 🎙️ Arunmozhi, K. S. Chithra / 🎼 Deva / 📝 Kasthuri Raja", duration: 332 },
{ file: "Solakkaattu.m4a", details: "🎬 En Aasai Rasave (1998) / 🎙️ P. Unnikrishnan, Swarnalatha / 🎼 Deva / 📝 Kasthuri Raja", duration: 351 },
{ file: "Yeh Panjaara Kooda.m4a", details: "🎬 En Aasai Rasave (1998) / 🎙️ Krishnaraj, Devi / 🎼 Deva / 📝 Kasthuri Raja", duration: 160 },
{ file: "Yennadi Nee.m4a", details: "🎬 En Aasai Rasave (1998) / 🎙️ Krishnaraj, Devi Neithiyar / 🎼 Deva / 📝 Kasthuri Raja", duration: 175 },
{ file: "Kadhal Kasakkuthaiya.m4a", details: "🎬 Aan Paavam (1985) / 🎙️ Ilaiyaraaja / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 263 },
{ file: "Kuyile Kuyile Poonguyile.m4a", details: "🎬 Aan Paavam (1985) / 🎙️ Malaysia Vasudevan, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Kuruvikkarambai Shanmugam", duration: 262 },
{ file: "Kattu Kuyilu.m4a", details: "🎬 Thalapathi (1991) / 🎙️ S. P. Balasubrahmanyam, K. J. Yesudas / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 330 },
{ file: "Rakkamma.m4a", details: "🎬 Thalapathi (1991) / 🎙️ S. P. Balasubrahmanyam, Swarnalatha / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 431 },
{ file: "Sundari kannal oru.m4a", details: "🎬 Thalapathi (1991) / 🎙️ S. P. Balasubrahmanyam, S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 433 },
{ file: "Ithu Oru Ponmalai.m4a", details: "🎬 Nizhalgal (1980) / 🎙️ S. P. Balasubrahmanyam / 🎼 Ilaiyaraaja / 📝 Vairamuthu", duration: 259 },
{ file: "Madai Thiranthu.m4a", details: "🎬 Nizhalgal (1980) / 🎙️ S. P. Balasubrahmanyam / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 261 },
{ file: "Poongathave Thaal.m4a", details: "🎬 Nizhalgal (1980) / 🎙️ Deepan Chakravarthy, Uma Ramanan / 🎼 Ilaiyaraaja / 📝 Gangai Amaran", duration: 261 },
{ file: "Maalai Soodum Vaelai.m4a", details: "🎬 Naan Mahaan Alla (1984) / 🎙️ S. P. Balasubrahmanyam, S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 266 },
{ file: "Andha Vaanam Enthan Kaiyil.m4a", details: "🎬 Gokulam (1993) / 🎙️ K. S. Chithra / 🎼 Sirpy / 📝 Pazhani Bharathi", duration: 235 },
{ file: "Chevvanthi Pooveduthen.m4a", details: "🎬 Gokulam (1993) / 🎙️ Unni Menon, P. Susheela / 🎼 Sirpy / 📝 Pazhani Bharathi", duration: 301 },
{ file: "Ponmaalaiyil.m4a", details: "🎬 Gokulam (1993) / 🎙️ Uma Ramanan / 🎼 Sirpy / 📝 Pazhani Bharathi", duration: 192 },
{ file: "Puthuroja Poothirukku.m4a", details: "🎬 Gokulam (1993) / 🎙️ Mano, Swarnalatha / 🎼 Sirpy / 📝 Pazhani Bharathi", duration: 189 },
{ file: "Therkke Adikkuthu Kaaththu.m4a", details: "🎬 Gokulam (1993) / 🎙️ K. S. Chithra / 🎼 Sirpy / 📝 Pazhani Bharathi", duration: 275 },
{ file: "Odugira Vandioda.m4a", details: "🎬 Mannukketha Maindan (1990) / 🎙️ A. R. Sheik Mohammed / 🎼 Deva / 📝 Kalidasan", duration: 250 },
{ file: "Sendhamani Kuyile.m4a", details: "🎬 Mannukketha Maindan (1990) / 🎙️ Mano, S. Janaki / 🎼 Deva / 📝 Kalidasan", duration: 297 },
{ file: "Jilla Mulukka.m4a", details: "🎬 Priyanka (1994) / 🎙️ Mano, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 310 },
{ file: "Vanakkuyile Kuyil.m4a", details: "🎬 Priyanka (1994) / 🎙️ S. P. Balasubrahmanyam / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 296 },
{ file: "Vettukili Vetti Vantha.m4a", details: "🎬 Priyanka (1994) / 🎙️ Mano, Swarnalatha / 🎼 Ilaiyaraaja / 📝 Pulamaipithan", duration: 369 },
{ file: "Kalayila.m4a", details: "🎬 Veeranadai (2000) / 🎙️ Krishnaraj, Jayalakshmi, Sabesh, Sushmitha, Amrutha, Yugendran, Prashanthini, Venkat Prabhu / 🎼 Deva / 📝 Na. Muthukumar", duration: 343 },
{ file: "Muthu Muttha.m4a", details: "🎬 Veeranadai (2000) / 🎙️ Sujatha Mohan / 🎼 Deva / 📝 Na. Muthukumar", duration: 245 },
{ file: "Usuravachen Mama.m4a", details: "🎬 Veeranadai (2000) / 🎙️ Swarnalatha / 🎼 Deva / 📝 Thamarai", duration: 195 },
{ file: "Kannil Unnai.m4a", details: "🎬 Kanave Kalaiyadhe (1999) / 🎙️ K. S. Chithra / 🎼 Deva / 📝 Vaali", duration: 359 },
{ file: "Kannodu Kannodu.m4a", details: "🎬 Kanave Kalaiyadhe (1999) / 🎙️ P. Unni Krishnan, Mahanadhi Shobana / 🎼 Deva / 📝 Vairamuthu", duration: 328 },
{ file: "Poosu Manjal female.m4a", details: "🎬 Kanave Kalaiyadhe (1999) / 🎙️ Anuradha Paudwal / 🎼 Deva / 📝 Vairamuthu", duration: 345 },
{ file: "Poosu Manjal male.m4a", details: "🎬 Kanave Kalaiyadhe (1999) / 🎙️ Hariharan / 🎼 Deva / 📝 Vairamuthu", duration: 341 },
{ file: "Ninnukori Varanam.m4a", details: "🎬 Agni Natchathiram (1988) / 🎙️ K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 276 },
{ file: "Oru Poonga Vanam.m4a", details: "🎬 Agni Natchathiram (1988) / 🎙️ S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 264 },
{ file: "Roja Poo Adivanthathu.m4a", details: "🎬 Agni Natchathiram (1988) / 🎙️ S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 267 },
{ file: "Raaja Raajathi.m4a", details: "🎬 Agni Natchathiram (1988) / 🎙️ Ilaiyaraaja / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 281 },
{ file: "Thoongatha Vizhigal.m4a", details: "🎬 Agni Natchathiram (1988) / 🎙️ K. J. Yesudas, S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 280 },
{ file: "Vaa Vaa Anbe Anbe.m4a", details: "🎬 Agni Natchathiram (1988) / 🎙️ K. J. Yesudas, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 279 },
{ file: "Champagini.m4a", details: "📀 Champagini (2025) / 🎙️ Asal Kolaar / 🎼 Urban Thozha / 📝 Asal Kolaar", duration: 116 },
{ file: "Jorthaale.m4a", details: "📀 Jorthaale (2020) / 🎙️ Asal Kolaar, ofRo / 🎼 ofRo / 📝 Asal Kolaar", duration: 110 },
{ file: "Paiya Dei.m4a", details: "📀 Paiya Dei (2024) / 🎙️ Asal Kolaar / 🎼 Anand Kashinath / 📝 Asal Kolaar", duration: 155 },
{ file: "Vaanaambaa.m4a", details: "📀 Vaanaambaa (2020) / 🎙️ Asal Kolaar, ofRo / 🎼 ofRo / 📝 Asal Kolaar", duration: 167 },
{ file: "Adi Manjakilanka.m4a", details: "🎬 Taj Mahal (1999) / 🎙️ Ganga Sitharasu, Febi Mani, Theni Kunjarammal, Kanchana / 🎼 A. R. Rahman / 📝 Vairamuthu", duration: 175 },
{ file: "Eetchi Elumichi reprise.m4a", details: "🎬 Taj Mahal (1999) / 🎙️ Krishnaraj, Arundhathi, Raqeeb Alam / 🎼 A. R. Rahman / 📝 Vairamuthu", duration: 406 },
{ file: "Eetchi Elumichi.m4a", details: "🎬 Taj Mahal (1999) / 🎙️ Manoj, Arundhathi, Raqeeb Alam, Parthasarathy, Navin / 🎼 A. R. Rahman / 📝 Vairamuthu", duration: 406 },
{ file: "Karisal Tarisal.m4a", details: "🎬 Taj Mahal (1999) / 🎙️ M. G. Sreekumar, K. S. Chithra / 🎼 A. R. Rahman / 📝 Vairamuthu", duration: 355 },
{ file: "Kilakke Nanthavanam.m4a", details: "🎬 Taj Mahal (1999) / 🎙️ Ganga Sitharasu, Febi Mani, Kanchana, Theni Kunjarammal / 🎼 A. R. Rahman / 📝 Vairamuthu", duration: 168 },
{ file: "Kulliruthu Kulliruthu.m4a", details: "🎬 Taj Mahal (1999) / 🎙️ Unni Krishnan, Swarnalatha, R. Viswanathan / 🎼 A. R. Rahman / 📝 Vairamuthu", duration: 287 },
{ file: "Senkathay.m4a", details: "🎬 Taj Mahal (1999) / 🎙️ T. K. Kala, Richa Sharma / 🎼 A. R. Rahman / 📝 Vairamuthu", duration: 295 },
{ file: "Sotta Sotta female.m4a", details: "🎬 Taj Mahal (1999) / 🎙️ Sujatha Mohan / 🎼 A. R. Rahman / 📝 Vairamuthu", duration: 345 },
{ file: "Sotta Sotta male.m4a", details: "🎬 Taj Mahal (1999) / 🎙️ Srinivas / 🎼 A. R. Rahman / 📝 Vairamuthu", duration: 335 },
{ file: "Tirupatchi Aruvalle.m4a", details: "🎬 Taj Mahal (1999) / 🎙️ Palakkad Sreeram, Kalpana Raghavendhar, Clinton Cerejo, Chandran / 🎼 A. R. Rahman / 📝 Vairamuthu", duration: 417 },
{ file: "Oh Kathal Ennai.m4a", details: "🎬 Kodi Parakkuthu (1988) / 🎙️ S. P. Balasubrahmanyam, Vani Jairam / 🎼 Hamsalekha", duration: 256 },
{ file: "Selai Kattum.m4a", details: "🎬 Kodi Parakkuthu (1988) / 🎙️ S. P. Balasubrahmanyam, K. S. Chithra / 🎼 Hamsalekha", duration: 290 },
{ file: "Bharathikku.m4a", details: "🎬 Priyamudan (1998) / 🎙️ S. P. Balasubrahmanyam / 🎼 Deva / 📝 Ra. Ravishankar / 🎥 Vincent Selva", duration: 320 },
{ file: "Pooja Vaa.m4a", details: "🎬 Priyamudan (1998) / 🎙️ S. P. Balasubrahmanyam, K. S. Chithra / 🎼 Deva / 📝 Palani Bharathi / 🎥 Vincent Selva", duration: 371 },
{ file: "Whitulakkan.m4a", details: "🎬 Priyamudan (1998) / 🎙️ Deva / 🎼 Deva", duration: 272 },
{ file: "Mellisaiyae.m4a", details: "🎬 Mr. Romeo (1996) / 🎙️ Swarnalatha, Unni Menon, Srinivas, Sujatha Mohan / 🎼 A. R. Rahman / 📝 Vaali / 🎥 K. S. Ravi", duration: 371 },
{ file: "Romeo Attam Potal.m4a", details: "🎬 Mr. Romeo (1996) / 🎙️ Hariharan, Udit Narayan / 🎼 A. R. Rahman / 📝 Vaali / 🎥 K. S. Ravi", duration: 339 },
{ file: "Thaneerai Khadalikum.m4a", details: "🎬 Mr. Romeo (1996) / 🎙️ Sangeetha Sajith / 🎼 A. R. Rahman / 📝 Vaali / 🎥 K. S. Ravi", duration: 237 },
{ file: "En Meal Vizhundha Mazhai.m4a", details: "🎬 May Maadham (1994) / 🎙️ P. Jayachandran, K. S. Chithra / 🎼 A. R. Rahman / 📝 Vairamuthu / 🎥 Balu", duration: 300 },
{ file: "Maargazhi Poovea.m4a", details: "🎬 May Maadham (1994) / 🎙️ Shobha Shankar, Chorus / 🎼 A. R. Rahman / 📝 Vairamuthu / 🎥 Balu", duration: 380 },
{ file: "Madrasa Suthi Paakka.m4a", details: "🎬 May Maadham (1994) / 🎙️ Shahul Hameed, Swarnalatha, G. V. Prakash Kumar, Manorama / 🎼 A. R. Rahman / 📝 Vairamuthu / 🎥 Balu", duration: 291 },
{ file: "Minnalea En Vazhvin.m4a", details: "🎬 May Maadham (1994) / 🎙️ S. P. Balasubrahmanyam / 🎼 A. R. Rahman / 📝 Vairamuthu / 🎥 Balu", duration: 337 },
{ file: "En Kannukoru Nilava.m4a", details: "🎬 Aararo Aariraro (1989) / 🎙️ S. P. Balasubrahmanyam, S. Janaki, Chorus / 🎼 K. Bhagyaraj / 📝 Vaali / 🎥 K. Bhagyaraj", duration: 271 },
{ file: "Adho Mega Oorvalam.m4a", details: "🎬 Eeramana Rojave (1991) / 🎙️ Mano, Sunanda / 🎼 Ilaiyaraaja / 📝 Pulamaipithan / 🎥 Keyaar", duration: 309 },
{ file: "Kalakalakum Maniosai.m4a", details: "🎬 Eeramana Rojave (1991) / 🎙️ Mano, S. Janaki / 🎼 Ilaiyaraaja / 📝 Piraisoodan / 🎥 Keyaar", duration: 293 },
{ file: "Thendral Kaatre.m4a", details: "🎬 Eeramana Rojave (1991) / 🎙️ K. J. Yesudas, S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 Keyaar", duration: 295 },
{ file: "Vaa Vaa Anbe poojai.m4a", details: "🎬 Eeramana Rojave (1991) / 🎙️ K. J. Yesudas, S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 Keyaar", duration: 306 },
{ file: "Vanna Poongavanam.m4a", details: "🎬 Eeramana Rojave (1991) / 🎙️ K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Muthulingam / 🎥 Keyaar", duration: 290 },
{ file: "Chinna Purave.m4a", details: "🎬 Kannaal Pesavaa (2000) / 🎙️ P. Unnikrishnan / 🎼 Deva / 📝 M. Raaj Khanna / 🎥 M. Raaj Khanna", duration: 308 },
{ file: "Kan Azhage female.m4a", details: "🎬 Kannaal Pesavaa (2000) / 🎙️ Sujatha Mohan / 🎼 Deva / 📝 M. Raaj Khanna / 🎥 M. Raaj Khanna", duration: 348 },
{ file: "Kan Azhage.m4a", details: "🎬 Kannaal Pesavaa (2000) / 🎙️ Hariharan / 🎼 Deva / 📝 M. Raaj Khanna / 🎥 M. Raaj Khanna", duration: 346 },
{ file: "Mathalathai Kottu.m4a", details: "🎬 Kannaal Pesavaa (2000) / 🎙️ Anuradha Sriram / 🎼 Deva / 📝 M. Raaj Khanna / 🎥 M. Raaj Khanna", duration: 314 },
{ file: "Nenjikulla.m4a", details: "🎬 Kannaal Pesavaa (2000) / 🎙️ Sujatha Mohan / 🎼 Deva / 📝 M. Raaj Khanna / 🎥 M. Raaj Khanna", duration: 328 },
{ file: "Thotta Chinunki pola.m4a", details: "🎬 Kannaal Pesavaa (2000) / 🎙️ Krishnaraj, Swarnalatha / 🎼 Deva / 📝 M. Raaj Khanna / 🎥 M. Raaj Khanna", duration: 282 },
{ file: "Arithaaratha Poosikolla Aasai.m4a", details: "🎬 Avatharam (1995) / 🎙️ Ilaiyaraaja, S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 Nassar / 🏷️ Echo", duration: 348 },
{ file: "Oru Gundu Mani Kulunguthadi.m4a", details: "🎬 Avatharam (1995) / 🎙️ Ilaiyaraaja / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 Nassar / 🏷️ Echo", duration: 298 },
{ file: "Thendral Vanthu Theendumbothu.m4a", details: "🎬 Avatharam (1995) / 🎙️ Ilaiyaraaja, S. Janaki, Ganesh Manivannan / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 Nassar / 🏷️ Echo", duration: 318 },
{ file: "Adhikalaiyil Shevalai.m4a", details: "🎬 Nee Varuvai Ena (1999) / 🎙️ P. Unnikrishnan, Sujatha Mohan / 🎼 S. A. Rajkumar / 📝 Ramesh Vaidya / 🎥 Rajakumaran / 🏷️ Sa Re Ga Ma, Star Music", duration: 284 },
{ file: "Oru Devathai Vanthu female .m4a", details: "🎬 Nee Varuvai Ena (1999) / 🎙️ K. S. Chithra / 🎼 S. A. Rajkumar / 📝 Ramesh Vaidya / 🎥 Rajakumaran / 🏷️ Sa Re Ga Ma, Star Music", duration: 248 },
{ file: "Oru Devathai Vanthu Vittaal male.m4a", details: "🎬 Nee Varuvai Ena (1999) / 🎙️ Hariharan / 🎼 S. A. Rajkumar / 📝 Ramesh Vaidya / 🎥 Rajakumaran / 🏷️ Sa Re Ga Ma, Star Music", duration: 284 },
{ file: "Parthu Parthu female.m4a", details: "🎬 Nee Varuvai Ena (1999) / 🎙️ K. S. Chithra / 🎼 S. A. Rajkumar / 📝 Pa. Vijay / 🎥 Rajakumaran / 🏷️ Sa Re Ga Ma, Star Music", duration: 272 },
{ file: "Parthu Parthu male.m4a", details: "🎬 Nee Varuvai Ena (1999) / 🎙️ S. P. Balasubrahmanyam / 🎼 S. A. Rajkumar / 📝 Pa. Vijay / 🎥 Rajakumaran / 🏷️ Sa Re Ga Ma, Star Music", duration: 272 },
{ file: "Poonguil Pattu Putichirukka.m4a", details: "🎬 Nee Varuvai Ena (1999) / 🎙️ Arunmozhi, Harini / 🎼 S. A. Rajkumar / 📝 Viveka / 🎥 Rajakumaran / 🏷️ Sa Re Ga Ma, Star Music", duration: 247 },
{ file: "Nandri Solla Unakku 1.m4a", details: "🎬 Marumalarchi (1998) / 🎙️ Hariharan, Amrutha / 🎼 S. A. Rajkumar / 📝 Vaali / 🎥 Bharathi / 🏷️ Five Star Audio", duration: 221 },
{ file: "Nandri Solla Unaku 2.m4a", details: "🎬 Marumalarchi (1998) / 🎙️ P. Unnikrishnan, K. S. Chithra / 🎼 S. A. Rajkumar / 📝 Vaali / 🎥 Bharathi / 🏷️ Five Star Audio", duration: 221 },
{ file: "Rettaikili.m4a", details: "🎬 Marumalarchi (1998) / 🎙️ Mano, Swarnalatha, T. K. Kala / 🎼 S. A. Rajkumar / 📝 Palani Bharathi / 🎥 Bharathi / 🏷️ Five Star Audio", duration: 263 },
{ file: "Clio Paattra.m4a", details: "🎬 Unakkaga Ellam Unakkaga (1999) / 🎙️ Yuvan Shankar Raja, Timmy, Sowmya Raoh / 🎼 Yuvan Shankar Raja / 📝 Viveka / 🎥 Sundar C", duration: 291 },
{ file: "Dhuniyaa.m4a", details: "🎬 Unakkaga Ellam Unakkaga (1999) / 🎙️ Srinivas, Sandeep / 🎼 Yuvan Shankar Raja / 📝 Kalaikumar / 🎥 Sundar C", duration: 276 },
{ file: "Monaalisa.m4a", details: "🎬 Unakkaga Ellam Unakkaga (1999) / 🎙️ Devan Ekambaram, Anuradha Sriram / 🎼 Yuvan Shankar Raja / 📝 Viveka / 🎥 Sundar C", duration: 290 },
{ file: "Thulli Thulli.m4a", details: "🎬 Unakkaga Ellam Unakkaga (1999) / 🎙️ S. P. B. Charan, Sujatha Mohan / 🎼 Yuvan Shankar Raja / 📝 Viveka / 🎥 Sundar C", duration: 275 },
{ file: "Vennilaa.m4a", details: "🎬 Unakkaga Ellam Unakkaga (1999) / 🎙️ Hariharan / 🎼 Yuvan Shankar Raja / 📝 Palani Bharathi / 🎥 Sundar C", duration: 305 },
{ file: "Alolam Kili Koottile.m4a", details: "🎬 Siraichalai (1996) / 🎙️ S. P. Balasubrahmanyam, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Arivumathi / 🎥 Priyadarshan", duration: 300 },
{ file: "Sempoove Poove.m4a", details: "🎬 Siraichalai (1996) / 🎙️ S. P. Balasubrahmanyam, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Arivumathi / 🎥 Priyadarshan", duration: 298 },
{ file: "Ennai Thottu Vittu.m4a", details: "🎬 Poomaname Vaa (1999) / 🎙️ S. P. Balasubrahmanyam, K. S. Chithra / 🎼 Sirpy / 📝 Palani Bharathi / 🎥 V. Azhagappan", duration: 267 },
{ file: "Kaathu Kulir kaathu.m4a", details: "🎬 Poomaname Vaa (1999) / 🎙️ S. P. Balasubrahmanyam, Swarnalatha / 🎼 Sirpy / 📝 Palani Bharathi / 🎥 V. Azhagappan", duration: 253 },
{ file: "Adikkudhu Kuliru.m4a", details: "🎬 Mannan (1992) / 🎙️ S. Janaki, Rajinikanth / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 P. Vasu / 🏷️ Pyramid", duration: 314 },
{ file: "Amma Endrazhaikadha.m4a", details: "🎬 Mannan (1992) / 🎙️ K. J. Yesudas / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 P. Vasu / 🏷️ Pyramid", duration: 293 },
{ file: "Gumthalakkadi.m4a", details: "🎬 Mannan (1992) / 🎙️ S. P. Balasubrahmanyam / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 P. Vasu / 🏷️ Pyramid", duration: 304 },
{ file: "Mannar Mannane.m4a", details: "🎬 Mannan (1992) / 🎙️ S. P. Balasubrahmanyam, S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 P. Vasu / 🏷️ Pyramid", duration: 163 },
{ file: "Rajadhi Raja un.m4a", details: "🎬 Mannan (1992) / 🎙️ S. P. Balasubrahmanyam, Swarnalatha / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 P. Vasu / 🏷️ Pyramid", duration: 299 },
{ file: "Sandiraniyae bit.m4a", details: "🎬 Mannan (1992) / 🎙️ S. P. Balasubrahmanyam / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 P. Vasu / 🏷️ Pyramid", duration: 119 },
{ file: "En Swasa Kaatre.m4a", details: "🎬 En Swasa Kaatre (1999) / 🎙️ M. G. Sreekumar, K. S. Chithra / 🎼 A. R. Rahman / 📝 Vairamuthu / 🎥 K. S. Ravi / 🏷️ Pyramid", duration: 315 },
{ file: "Jumballakka.m4a", details: "🎬 En Swasa Kaatre (1999) / 🎙️ Rafee / 🎼 A. R. Rahman / 📝 Vairamuthu / 🎥 K. S. Ravi / 🏷️ Pyramid", duration: 379 },
{ file: "Nayagra.m4a", details: "🎬 En Swasa Kaatre (1999) / 🎙️ Palakkad Sreeram, Harini, Anupama / 🎼 A. R. Rahman / 📝 Vaali / 🎥 K. S. Ravi / 🏷️ Pyramid", duration: 301 },
{ file: "Oru Thuli.m4a", details: "🎬 En Swasa Kaatre (1999) / 🎙️ M. G. Sreekumar / 🎼 A. R. Rahman / 📝 Vairamuthu / 🎥 K. S. Ravi / 🏷️ Pyramid", duration: 348 },
{ file: "Theenadai.m4a", details: "🎬 En Swasa Kaatre (1999) / 🎙️ S. P. Balasubrahmanyam, K. S. Chithra / 🎼 A. R. Rahman / 📝 Vairamuthu / 🎥 K. S. Ravi / 🏷️ Pyramid", duration: 408 },
{ file: "Thirakkaatha.m4a", details: "🎬 En Swasa Kaatre (1999) / 🎙️ P. Unnikrishnan, K. S. Chithra / 🎼 A. R. Rahman / 📝 Vairamuthu / 🎥 K. S. Ravi / 🏷️ Pyramid", duration: 429 },
{ file: "Kaatraga Varuvaya.m4a", details: "🎬 Unnai Thedi (1999) / 🎙️ Naveen / 🎼 Deva / 📝 Ra. Ravishankar / 🎥 Sundar C. / 🏷️ Pyramid Music", duration: 304 },
{ file: "Maalavika.m4a", details: "🎬 Unnai Thedi (1999) / 🎙️ Hariharan, K. S. Chithra / 🎼 Deva / 📝 Kalaikumar / 🎥 Sundar C. / 🏷️ Pyramid Audio", duration: 302 },
{ file: "Naalai Kaalai.m4a", details: "🎬 Unnai Thedi (1999) / 🎙️ Hariharan / 🎼 Deva / 📝 Palani Bharathi / 🎥 Sundar C. / 🏷️ Pyramid Audio", duration: 306 },
{ file: "Neethana Neethana.m4a", details: "🎬 Unnai Thedi (1999) / 🎙️ Hariharan, Sujatha / 🎼 Deva / 📝 Palani Bharathi / 🎥 Sundar C. / 🏷️ Pyramid Audio", duration: 293 },
{ file: "Poorale.m4a", details: "🎬 Unnai Thedi (1999) / 🎙️ Hariharan / 🎼 Deva / 📝 Vaali / 🎥 Sundar C. / 🏷️ Pyramid Audio", duration: 291 },
{ file: "Adi Aathukulla Atthimaram.m4a", details: "🎬 Rajadhi Raja (1989) / 🎙️ S. P. Balasubrahmanyam / 🎼 Ilaiyaraaja / 📝 Ilaiyaraaja / 🎥 R. Sundarrajan", duration: 383 },
{ file: "Enkitta Modhadhe.m4a", details: "🎬 Rajadhi Raja (1989) / 🎙️ Mano, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Ponnadiyan / 🎥 R. Sundarrajan / 🏷️ Sony Music Entertainment India Pvt. Ltd. / Echo Recording Co. Pvt. Ltd.", duration: 297 },
{ file: "Maama Un Ponna Kodu.m4a", details: "🎬 Rajadhi Raja (1989) / 🎙️ S. P. Balasubrahmanyam / 🎼 Ilaiyaraaja / 📝 Gangai Amaran / 🎥 R. Sundarrajan", duration: 269 },
{ file: "Malayaala Karaiyoram.m4a", details: "🎬 Rajadhi Raja (1989) / 🎙️ Mano / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 R. Sundarrajan", duration: 287 },
{ file: "Meenamma Meenamma.m4a", details: "🎬 Rajadhi Raja (1989) / 🎙️ Mano, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Piraisoodan / 🎥 R. Sundarrajan", duration: 285 },
{ file: "Un Nenja Thottu Sollu.m4a", details: "🎬 Rajadhi Raja (1989) / 🎙️ P. Susheela, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Gangai Amaran / 🎥 R. Sundarrajan", duration: 281 },
{ file: "Vaa Vaa Manjal Malare.m4a", details: "🎬 Rajadhi Raja (1989) / 🎙️ Mano, S. P. Sailaja / 🎼 Ilaiyaraaja / 📝 Ilaiyaraaja / 🎥 R. Sundarrajan", duration: 279 },
{ file: "Isthanbul.m4a", details: "🎬 Mazhai (2005) / 🎙️ Jassie Gift, Kalpana / 🎼 Devi Sri Prasad / 📝 Vairamuthu / 🎥 Rajkumar", duration: 254 },
{ file: "Kuchikaruvadu.m4a", details: "🎬 Mazhai (2005) / 🎙️ Tippu, Srilekha Parthasarathy / 🎼 Devi Sri Prasad / 📝 Vairamuthu / 🎥 Rajkumar", duration: 330 },
{ file: "Mannile.m4a", details: "🎬 Mazhai (2005) / 🎙️ S. P. B. Charan, Sumangali / 🎼 Devi Sri Prasad / 📝 Vairamuthu / 🎥 Rajkumar", duration: 324 },
{ file: "Muthu Mazhaiye.m4a", details: "🎬 Mazhai (2005) / 🎙️ Sagar, Sumangali / 🎼 Devi Sri Prasad / 📝 Vairamuthu / 🎥 Rajkumar", duration: 83 },
{ file: "Nee Varumbodhu.m4a", details: "🎬 Mazhai (2005) / 🎙️ K. S. Chithra, Kalpana, Raqueeb Alam / 🎼 Devi Sri Prasad / 📝 Vairamuthu / 🎥 Rajkumar", duration: 335 },
{ file: "Thappe Ille.m4a", details: "🎬 Mazhai (2005) / 🎙️ S. P. Balasubrahmanyam, Harini / 🎼 Devi Sri Prasad / 📝 Vairamuthu / 🎥 Rajkumar", duration: 236 },
{ file: "Enga Vacha Enga vacha.m4a", details: "🎬 Pattikattan (1989) / 🎙️ Malaysia Vasudevan, K. S. Chithra / 🎼 Shankar–Ganesh / 📝 Vaali / 🎥 T. S. Krishnakumar", duration: 261 },
{ file: "Kilakku Sivakiyile.m4a", details: "🎬 Seevalaperi Pandi (1994) / 🎙️ Rajagopal, Sujatha Mohan, P. G. Srikanth / 🎼 Adithyan / 📝 K. Rajeshwar / 🎥 Pratap Pothen", duration: 231 },
{ file: "Oyila Paadum Paatule.m4a", details: "🎬 Seevalaperi Pandi (1994) / 🎙️ K. S. Chithra / 🎼 Adithyan / 📝 Vairamuthu / 🎥 Pratap Pothen", duration: 383 },
{ file: "Kadhala Kadhala.m4a", details: "🎬 Avvai Shanmugi (1996) / 🎙️ Hariharan, Sujatha / 🎼 Deva / 📝 Vaali / 🎥 K. S. Ravikumar", duration: 346 },
{ file: "Kadhali Kadhali.m4a", details: "🎬 Avvai Shanmugi (1996) / 🎙️ Hariharan / 🎼 Deva / 📝 Vaali / 🎥 K. S. Ravikumar", duration: 345 },
{ file: "Kalyanam Katcheri.m4a", details: "🎬 Avvai Shanmugi (1996) / 🎙️ S. P. Balasubrahmanyam / 🎼 Deva / 📝 Vaali / 🎥 K. S. Ravikumar", duration: 329 },
{ file: "Rukku Rukku Rukku.m4a", details: "🎬 Avvai Shanmugi (1996) / 🎙️ Kamal Haasan, Sujatha / 🎼 Deva / 📝 Vaali / 🎥 K. S. Ravikumar", duration: 354 },
{ file: "Velai Velai.m4a", details: "🎬 Avvai Shanmugi (1996) / 🎙️ S. P. Balasubrahmanyam / 🎼 Deva / 📝 Vaali / 🎥 K. S. Ravikumar", duration: 325 },
{ file: "Hey Unnaithaane.m4a", details: "🎬 Kadhal Parisu (1987) / 🎙️ S. P. Balasubrahmanyam, S. Janaki / 🎼 Ilaiyaraaja / 📝 Vairamuthu / 🎥 A. Jagannathan", duration: 240 },
{ file: "Jaadhi Illai.m4a", details: "🎬 Kadhal Parisu (1987) / 🎙️ Malaysia Vasudevan / 🎼 Ilaiyaraaja / 📝 Gangai Amaran / 🎥 A. Jagannathan", duration: 240 },
{ file: "Kadhal Maharani Kavidhai.m4a", details: "🎬 Kadhal Parisu (1987) / 🎙️ S. P. Balasubrahmanyam, S. Janaki / 🎼 Ilaiyaraaja / 📝 Muthulingam / 🎥 A. Jagannathan", duration: 240 },

{ file: "Journey.m4a", details: "🎬 Jaanu (2020) / 🎙️ Pradeep Kumar / 🎼 Govind Vasantha / 📝 Karthik Netha / 🎥 C. Prem Kumar", duration: 367 },
{ file: "Ding Dang Dang.m4a", details: "🎬 Panakkaran (1990) / 🎙️ S. P. Balasubrahmanyam, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Pulamaipithan / 🎥 P. Vasu", duration: 297 },
{ file: "Maraththa Vechchavan.m4a", details: "🎬 Panakkaran (1990) / 🎙️ Ilaiyaraaja / 🎼 Ilaiyaraaja / 📝 Ilaiyaraaja / 🎥 P. Vasu", duration: 239 },
{ file: "Nooru Varusham (Female).m4a", details: "🎬 Panakkaran (1990) / 🎙️ S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 P. Vasu", duration: 271 },
{ file: "Nooru Varusham (Male).m4a", details: "🎬 Panakkaran (1990) / 🎙️ Mano / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 P. Vasu", duration: 267 },
{ file: "Silence Silence.m4a", details: "🎬 Panakkaran (1990) / 🎙️ S. P. Balasubrahmanyam, S. Janaki / 🎼 Ilaiyaraaja / 📝 Pulamaipithan / 🎥 P. Vasu", duration: 279 },
{ file: "Ullukulla Chakaravarthy.m4a", details: "🎬 Panakkaran (1990) / 🎙️ Ilaiyaraaja / 🎼 Ilaiyaraaja / 📝 Ilaiyaraaja / 🎥 P. Vasu", duration: 272 },
{ file: "Kanakozhikku Kaluthula Vellai.m4a", details: "🎬 Suyamvaram (1999) / 🎙️ Anuradha Sriram, Sabesan / 🎼 Deva / 📝 Ponniyin Selvan / 🎥 Various Directors", duration: 314 },
{ file: "Margazhi Maasathu.m4a", details: "🎬 Suyamvaram (1999) / 🎙️ S. P. Balasubrahmanyam, Mano, Unnikrishnan, Swarnalatha, Sujatha Mohan / 🎼 S. A. Rajkumar / 📝 Palani Bharathi / 🎥 Various Directors", duration: 453 },
{ file: "Sekka Sevantha Valea.m4a", details: "🎬 Suyamvaram (1999) / 🎙️ Hariharan, Sujatha Mohan / 🎼 Sirpy / 📝 Palani Bharathi / 🎥 Various Directors", duration: 304 },
{ file: "Kaadhala Kaadhala.m4a", details: "🎬 Suryavamsam (1997) / 🎙️ Hariharan, Swarnalatha / 🎼 S. A. Rajkumar / 📝 Palani Bharathi / 🎥 Vikraman / 🏷️ The Best Audio", duration: 278 },
{ file: "Natchathira Jannalil.m4a", details: "🎬 Suryavamsam (1997) / 🎙️ Mano, Sunandha / 🎼 S. A. Rajkumar / 📝 Mu. Metha / 🎥 Vikraman / 🏷️ Star Music", duration: 295 },
{ file: "Rosapoo-F.m4a", details: "🎬 Suryavamsam (1997) / 🎙️ Sujatha Mohan / 🎼 S. A. Rajkumar / 📝 Ra. Ravishankar / 🎥 Vikraman / 🏷️ Star Music", duration: 236 },
{ file: "Rosapoo-M.m4a", details: "🎬 Suryavamsam (1997) / 🎙️ Hariharan / 🎼 S. A. Rajkumar / 📝 Ra. Ravishankar / 🎥 Vikraman / 🏷️ Star Music", duration: 250 },
{ file: "Salakku Salakku Selai.m4a", details: "🎬 Suryavamsam (1997) / 🎙️ Arun Mozhi, Sujatha / 🎼 S. A. Rajkumar / 📝 Ra. Ravishankar / 🎥 Vikraman / 🏷️ Star Music", duration: 241 },
{ file: "Marutha Azhagaro.m4a", details: "🎬 Sundara Purushan (1996) / 🎙️ K. S. Chithra / 🎼 Sirpy / 📝 Vairamuthu / 🎥 Sabapathy Dekshinamurthy / 🏷️ The Best Audio", duration: 288 },
{ file: "Raja Rajane.m4a", details: "🎬 Sundara Purushan (1996) / 🎙️ Sirpy, J. Livingston, Geetha / 🎼 Sirpy / 📝 Kalidasan / 🎥 Sabapathy Dekshinamurthy / 🏷️ The Best Audio", duration: 274 },
{ file: "Chanda O Chanda.m4a", details: "🎬 Kannedhirey Thondrinal (1998) / 🎙️ Harini / 🎼 Deva / 📝 Vairamuthu / 🎥 Ravichandran / 🏷️ The Best Audio", duration: 319 },
{ file: "Chinna Chinna Kiliye.m4a", details: "🎬 Kannedhirey Thondrinal (1998) / 🎙️ Hariharan, Anuradha Sriram, Mahanadhi Shobana / 🎼 Deva / 📝 Vairamuthu / 🎥 Ravichandran / 🏷️ The Best Audio", duration: 334 },
{ file: "Eshwara Vaanum Mannum.m4a", details: "🎬 Kannedhirey Thondrinal (1998) / 🎙️ Udit Narayan / 🎼 Deva / 📝 Vairamuthu / 🎥 Ravichandran / 🏷️ The Best Audio", duration: 321 },
{ file: "Kanave Kalaiyathe.m4a", details: "🎬 Kannedhirey Thondrinal (1998) / 🎙️ P. Unni Krishnan, K. S. Chitra / 🎼 Deva / 📝 Vairamuthu / 🎥 Ravichandran / 🏷️ The Best Audio", duration: 345 },
{ file: "Kothal Savadi Lady.m4a", details: "🎬 Kannedhirey Thondrinal (1998) / 🎙️ Sabesh / 🎼 Deva / 📝 Ponniyin Selvan / 🎥 Ravichandran / 🏷️ The Best Audio", duration: 276 },
{ file: "Salomiya.m4a", details: "🎬 Kannedhirey Thondrinal (1998) / 🎙️ Deva / 🎼 Deva / 📝 Vairamuthu / 🎥 Ravichandran / 🏷️ The Best Audio", duration: 291 },
{ file: "Nee Malaraa Malaraa.mp3", details: "🎬 Arputham (2002) / 🎙️ P. Unnikrishnan, K. S. Chithra / 🎼 Shiva / 📝 Pa. Vijay / 🎥 Arputhan / 🏷️ Super Good Films", duration: 274 },
{ file: "Pothunda Pothunda.mp3", details: "🎬 Arputham (2002) / 🎙️ Tippu / 🎼 Shiva / 📝 Pa. Vijay / 🎥 Arputhan / 🏷️ Super Good Films", duration: 321 },
{ file: "Deeyaalo Deeyaalo (Ava Mela Aasa).mp3", details: "🎬 Kayal (2014) / 🎙️ Orathanadu Gopu / 🎼 D. Imman / 📝 Yugabharathi / 🎥 Prabhu Solomon / 🏷️ Sony Music", duration: 212 },
{ file: "Unna Ippo Paakkanum.mp3", details: "🎬 Kayal (2014) / 🎙️ Haricharan, Vandana Srinivasan / 🎼 D. Imman / 📝 Yugabharathi / 🎥 Prabhu Solomon / 🏷️ Sony Music", duration: 263 },
{ file: "Thappe Ille.m4a", details: "🎬 Mazhai (2005) / 🎙️ S. P. Balasubrahmanyam, Harini / 🎼 Devi Sri Prasad / 📝 Vairamuthu / 🎥 Rajkumar", duration: 236 },
{ file: "Enga Vacha Enga vacha.m4a", details: "🎬 Pattikattan (1989) / 🎙️ Malaysia Vasudevan, K. S. Chithra / 🎼 Shankar–Ganesh / 📝 Vaali / 🎥 T. S. Krishnakumar", duration: 261 },
{ file: "Kilakku Sivakiyile.m4a", details: "🎬 Seevalaperi Pandi (1994) / 🎙️ Rajagopal, Sujatha Mohan, P. G. Srikanth / 🎼 Adithyan / 📝 K. Rajeshwar / 🎥 Pratap Pothen", duration: 231 },
{ file: "Oyila Paadum Paatule.m4a", details: "🎬 Seevalaperi Pandi (1994) / 🎙️ K. S. Chithra / 🎼 Adithyan / 📝 Vairamuthu / 🎥 Pratap Pothen", duration: 383 },
{ file: "Kadhala Kadhala.m4a", details: "🎬 Avvai Shanmugi (1996) / 🎙️ Hariharan, Sujatha / 🎼 Deva / 📝 Vaali / 🎥 K. S. Ravikumar", duration: 346 },
{ file: "Kadhali Kadhali.m4a", details: "🎬 Avvai Shanmugi (1996) / 🎙️ Hariharan / 🎼 Deva / 📝 Vaali / 🎥 K. S. Ravikumar", duration: 345 },
{ file: "Kalyanam Katcheri.m4a", details: "🎬 Avvai Shanmugi (1996) / 🎙️ S. P. Balasubrahmanyam / 🎼 Deva / 📝 Vaali / 🎥 K. S. Ravikumar", duration: 329 },
{ file: "Rukku Rukku Rukku.m4a", details: "🎬 Avvai Shanmugi (1996) / 🎙️ Kamal Haasan, Sujatha / 🎼 Deva / 📝 Vaali / 🎥 K. S. Ravikumar", duration: 354 },
{ file: "Velai Velai.m4a", details: "🎬 Avvai Shanmugi (1996) / 🎙️ S. P. Balasubrahmanyam / 🎼 Deva / 📝 Vaali / 🎥 K. S. Ravikumar", duration: 325 },
{ file: "Hey Unnaithaane.m4a", details: "🎬 Kadhal Parisu (1987) / 🎙️ S. P. Balasubrahmanyam, S. Janaki / 🎼 Ilaiyaraaja / 📝 Vairamuthu / 🎥 A. Jagannathan", duration: 240 },
{ file: "Jaadhi Illai.m4a", details: "🎬 Kadhal Parisu (1987) / 🎙️ Malaysia Vasudevan / 🎼 Ilaiyaraaja / 📝 Gangai Amaran / 🎥 A. Jagannathan", duration: 240 },
{ file: "Kadhal Maharani Kavidhai.m4a", details: "🎬 Kadhal Parisu (1987) / 🎙️ S. P. Balasubrahmanyam, S. Janaki / 🎼 Ilaiyaraaja / 📝 Muthulingam / 🎥 A. Jagannathan", duration: 240 },
{ file: "Journey.m4a", details: "🎬 Jaanu (2020) / 🎙️ Pradeep Kumar / 🎼 Govind Vasantha / 📝 Karthik Netha / 🎥 C. Prem Kumar", duration: 367 },
{ file: "Ding Dang Dang.m4a", details: "🎬 Panakkaran (1990) / 🎙️ S. P. Balasubrahmanyam, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Pulamaipithan / 🎥 P. Vasu", duration: 297 },
{ file: "Maraththa Vechchavan.m4a", details: "🎬 Panakkaran (1990) / 🎙️ Ilaiyaraaja / 🎼 Ilaiyaraaja / 📝 Ilaiyaraaja / 🎥 P. Vasu", duration: 239 },
{ file: "Nooru Varusham (Female).m4a", details: "🎬 Panakkaran (1990) / 🎙️ S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 P. Vasu", duration: 271 },
{ file: "Nooru Varusham (Male).m4a", details: "🎬 Panakkaran (1990) / 🎙️ Mano / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 P. Vasu", duration: 267 },
{ file: "Silence Silence.m4a", details: "🎬 Panakkaran (1990) / 🎙️ S. P. Balasubrahmanyam, S. Janaki / 🎼 Ilaiyaraaja / 📝 Pulamaipithan / 🎥 P. Vasu", duration: 279 },
{ file: "Ullukulla Chakaravarthy.m4a", details: "🎬 Panakkaran (1990) / 🎙️ Ilaiyaraaja / 🎼 Ilaiyaraaja / 📝 Ilaiyaraaja / 🎥 P. Vasu", duration: 272 },
{ file: "Kanakozhikku Kaluthula Vellai.m4a", details: "🎬 Suyamvaram (1999) / 🎙️ Anuradha Sriram, Sabesan / 🎼 Deva / 📝 Ponniyin Selvan / 🎥 Various Directors", duration: 314 },
{ file: "Margazhi Maasathu.m4a", details: "🎬 Suyamvaram (1999) / 🎙️ S. P. Balasubrahmanyam, Mano, Unnikrishnan, Swarnalatha, Sujatha Mohan / 🎼 S. A. Rajkumar / 📝 Palani Bharathi / 🎥 Various Directors", duration: 453 },
{ file: "Sekka Sevantha Valea.m4a", details: "🎬 Suyamvaram (1999) / 🎙️ Hariharan, Sujatha Mohan / 🎼 Sirpy / 📝 Palani Bharathi / 🎥 Various Directors", duration: 304 },
{ file: "Kaadhala Kaadhala.m4a", details: "🎬 Suryavamsam (1997) / 🎙️ Hariharan, Swarnalatha / 🎼 S. A. Rajkumar / 📝 Palani Bharathi / 🎥 Vikraman / 🏷️ The Best Audio", duration: 278 },
{ file: "Natchathira Jannalil.m4a", details: "🎬 Suryavamsam (1997) / 🎙️ Mano, Sunandha / 🎼 S. A. Rajkumar / 📝 Mu. Metha / 🎥 Vikraman / 🏷️ Star Music", duration: 295 },
{ file: "Rosapoo-F.m4a", details: "🎬 Suryavamsam (1997) / 🎙️ Sujatha Mohan / 🎼 S. A. Rajkumar / 📝 Ra. Ravishankar / 🎥 Vikraman / 🏷️ Star Music", duration: 236 },
{ file: "Rosapoo-M.m4a", details: "🎬 Suryavamsam (1997) / 🎙️ Hariharan / 🎼 S. A. Rajkumar / 📝 Ra. Ravishankar / 🎥 Vikraman / 🏷️ Star Music", duration: 250 },
{ file: "Salakku Salakku Selai.m4a", details: "🎬 Suryavamsam (1997) / 🎙️ Arun Mozhi, Sujatha / 🎼 S. A. Rajkumar / 📝 Ra. Ravishankar / 🎥 Vikraman / 🏷️ Star Music", duration: 241 },
{ file: "Marutha Azhagaro.m4a", details: "🎬 Sundara Purushan (1996) / 🎙️ K. S. Chithra / 🎼 Sirpy / 📝 Vairamuthu / 🎥 Sabapathy Dekshinamurthy / 🏷️ The Best Audio", duration: 288 },
{ file: "Raja Rajane.m4a", details: "🎬 Sundara Purushan (1996) / 🎙️ Sirpy, J. Livingston, Geetha / 🎼 Sirpy / 📝 Kalidasan / 🎥 Sabapathy Dekshinamurthy / 🏷️ The Best Audio", duration: 274 },
{ file: "Chanda O Chanda.m4a", details: "🎬 Kannedhirey Thondrinal (1998) / 🎙️ Harini / 🎼 Deva / 📝 Vairamuthu / 🎥 Ravichandran / 🏷️ The Best Audio", duration: 319 },
{ file: "Chinna Chinna Kiliye.m4a", details: "🎬 Kannedhirey Thondrinal (1998) / 🎙️ Hariharan, Anuradha Sriram, Mahanadhi Shobana / 🎼 Deva / 📝 Vairamuthu / 🎥 Ravichandran / 🏷️ The Best Audio", duration: 334 },
{ file: "Eshwara Vaanum Mannum.m4a", details: "🎬 Kannedhirey Thondrinal (1998) / 🎙️ Udit Narayan / 🎼 Deva / 📝 Vairamuthu / 🎥 Ravichandran / 🏷️ The Best Audio", duration: 321 },
{ file: "Kanave Kalaiyathe.m4a", details: "🎬 Kannedhirey Thondrinal (1998) / 🎙️ P. Unni Krishnan, K. S. Chitra / 🎼 Deva / 📝 Vairamuthu / 🎥 Ravichandran / 🏷️ The Best Audio", duration: 345 },
{ file: "Kothal Savadi Lady.m4a", details: "🎬 Kannedhirey Thondrinal (1998) / 🎙️ Sabesh / 🎼 Deva / 📝 Ponniyin Selvan / 🎥 Ravichandran / 🏷️ The Best Audio", duration: 276 },
{ file: "Salomiya.m4a", details: "🎬 Kannedhirey Thondrinal (1998) / 🎙️ Deva / 🎼 Deva / 📝 Vairamuthu / 🎥 Ravichandran / 🏷️ The Best Audio", duration: 291 },
{ file: "Nee Malaraa Malaraa.mp3", details: "🎬 Arputham (2002) / 🎙️ P. Unnikrishnan, K. S. Chithra / 🎼 Shiva / 📝 Pa. Vijay / 🎥 Arputhan / 🏷️ Super Good Films", duration: 274 },
{ file: "Pothunda Pothunda.mp3", details: "🎬 Arputham (2002) / 🎙️ Tippu / 🎼 Shiva / 📝 Pa. Vijay / 🎥 Arputhan / 🏷️ Super Good Films", duration: 321 },
{ file: "Deeyaalo Deeyaalo (Ava Mela Aasa).mp3", details: "🎬 Kayal (2014) / 🎙️ Orathanadu Gopu / 🎼 D. Imman / 📝 Yugabharathi / 🎥 Prabhu Solomon / 🏷️ Sony Music", duration: 212 },
{ file: "Unna Ippo Paakkanum.mp3", details: "🎬 Kayal (2014) / 🎙️ Haricharan, Vandana Srinivasan / 🎼 D. Imman / 📝 Yugabharathi / 🎥 Prabhu Solomon / 🏷️ Sony Music", duration: 263 },
{ file: "Unnai Ninaithu naan.mp3", details: "🎬 Ninaithen Vandhai (1998) / 🎙️ S. P. Balasubrahmanyam, K. S. Chithra, Sujatha / 🎼 Deva / 📝 Vaali / 🎥 K. Selva Bharathy", duration: 240 },
{ file: "Vanna Nilave.mp3", details: "🎬 Ninaithen Vandhai (1998) / 🎙️ Hariharan / 🎼 Deva / 📝 Palani Bharathi / 🎥 K. Selva Bharathy", duration: 240 },
{ file: "Enthen Kuilenge.mp3", details: "🎬 Kannukkul Nilavu (2000) / 🎙️ P. Unni Krishnan, Anuradha Sriram / 🎼 Ilaiyaraaja / 📝 Pazhani Bharathi / 🎥 Fazil", duration: 240 },
{ file: "Nilavu Pattu.mp3", details: "🎬 Kannukkul Nilavu (2000) / 🎙️ Hariharan / 🎼 Ilaiyaraaja / 📝 Palani Bharathi / 🎥 Fazil", duration: 240 },
{ file: "Oru Naal Oru Kanavu.mp3", details: "🎬 Kannukkul Nilavu (2000) / 🎙️ K. J. Yesudas, Anuradha Sriram / 🎼 Ilaiyaraaja / 📝 Palani Bharathi / 🎥 Fazil", duration: 240 },
{ file: "Roja Poonthottam.mp3", details: "🎬 Kannukkul Nilavu (2000) / 🎙️ P. Unnikrishnan, Anuradha Sriram / 🎼 Ilaiyaraaja / 📝 Palani Bharathi / 🎥 Fazil", duration: 294 },
{ file: "Un Punagai Pothumadi.mp3", details: "🎬 Pass Mark (1993) / 🎙️ S. P. Balasubrahmanyam, K. S. Chithra / 🎼 Deva / 📝 Vairamuthu / 🎥 V. Balakrishnan", duration: 240 },
{ file: "Yerikayya Yerikayya.mp3", details: "🎬 Pass Mark (1993) / 🎙️ Mano, K. S. Chithra / 🎼 Deva / 📝 Vairamuthu", duration: 240 },
{ file: "Guli Mata Tamil.mp3", details: "🎬 Guli Mata (Tamil Version, 2023) / 🎙️ Eric Fernando, Kiru / 🎼 Eric Fernando", duration: 118 },
{ file: "Damaku Damakkudam.mp3", details: "🎬 Azhagi (2002) / 🎙️ Bhavatharini, Chorus / 🎼 Ilaiyaraaja / 📝 Palani Bharathi / 🎥 Thangar Bachan", duration: 308 },
{ file: "Kuruvi Kodanja.mp3", details: "🎬 Azhagi (2002) / 🎙️ Pushpavanam Kuppusamy, Swarnalatha / 🎼 Ilaiyaraaja / 📝 Palani Bharathi / 🎥 Thangar Bachan", duration: 275 },
{ file: "Oliyile Therivadhu Devadhaya.mp3", details: "🎬 Azhagi (2002) / 🎙️ Karthik, Bhavatharini / 🎼 Ilaiyaraaja / 📝 Ilaiyaraaja / 🎥 Thangar Bachan", duration: 306 },
{ file: "Paattu Solli Paada Solli.mp3", details: "🎬 Azhagi (2002) / 🎙️ Sadhana Sargam / 🎼 Ilaiyaraaja / 📝 Ilaiyaraaja / 🎥 Thangar Bachan", duration: 301 },
{ file: "Un Kuthama En Kuthama.mp3", details: "🎬 Azhagi (2002) / 🎙️ Ilaiyaraaja / 🎼 Ilaiyaraaja / 📝 Ilaiyaraaja / 🎥 Thangar Bachan", duration: 348 },
{ file: "Ananda Ragam Ketkum Kaalam.mp3", details: "🎬 Panneer Pushpangal (1981) / 🎙️ Uma Ramanan / 🎼 Ilaiyaraaja / 📝 Gangai Amaran / 🎥 P. Vasu, Santhana Bharathi", duration: 266 },
{ file: "Kodai Kaala Kaatre.mp3", details: "🎬 Panneer Pushpangal (1981) / 🎙️ Malaysia Vasudevan / 🎼 Ilaiyaraaja / 📝 Gangai Amaran / 🎥 P. Vasu, Santhana Bharathi", duration: 307 },
{ file: "Poonthalir Aada.mp3", details: "🎬 Panneer Pushpangal (1981) / 🎙️ S. P. Balasubrahmanyam, S. Janaki / 🎼 Ilaiyaraaja / 📝 Gangai Amaran / 🎥 P. Vasu, Santhana Bharathi", duration: 285 },
{ file: "Adi Yaarathu.mp3", details: "🎬 Mettukudi (1996) / 🎙️ Mano, K. S. Chithra / 🎼 Sirpy / 📝 Palani Bharathi / 🎥 Sundar C.", duration: 301 },
{ file: "Anbulla Mannavane.mp3", details: "🎬 Mettukudi (1996) / 🎙️ Mano, Swarnalatha / 🎼 Sirpy / 📝 Palani Bharathi / 🎥 S. Sundar C.", duration: 314 },
{ file: "Mana Madurai.mp3", details: "🎬 Mettukudi (1996) / 🎙️ Krishnachander, Swarnalatha / 🎼 Sirpy / 📝 Palani Bharathi / 🎥 Sundar C.", duration: 297 },
{ file: "Velvatta Velvatta.mp3", details: "🎬 Mettukudi (1996) / 🎙️ Mano, K. S. Chithra / 🎼 Sirpy / 📝 Palani Bharathi / 🎥 Sundar C.", duration: 302 },
{ file: "Poraney Poraney.mp3", details: "🎬 Vaagai Sooda Vaa (2011) / 🎙️ Ranjith, Neha Bhasin / 🎼 Ghibran / 📝 Karthik Netha / 🎥 A. Sarkunam", duration: 315 },
{ file: "Sara Sara Saara Kathu.mp3", details: "🎬 Vaagai Sooda Vaa (2011) / 🎙️ Chinmayi / 🎼 Ghibran / 📝 Vairamuthu / 🎥 A. Sarkunam", duration: 299 },
{ file: "Chinna Chinna Vanna Kuyil.mp3", details: "🎬 Mouna Ragam (1986) / 🎙️ S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 Mani Ratnam", duration: 266 },
{ file: "Mandram Vandha Thendralukku.mp3", details: "🎬 Mouna Ragam (1986) / 🎙️ S. P. Balasubrahmanyam / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 Mani Ratnam", duration: 287 },
{ file: "Nilaave Vaa.mp3", details: "🎬 Mouna Ragam (1986) / 🎙️ S. P. Balasubrahmanyam / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 Mani Ratnam", duration: 277 },
{ file: "Oho Megam Vandhadho.mp3", details: "🎬 Mouna Ragam (1986) / 🎙️ S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 Mani Ratnam", duration: 267 },
{ file: "Panivizhum Iravu.mp3", details: "🎬 Mouna Ragam (1986) / 🎙️ S. P. Balasubrahmanyam, S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 Mani Ratnam", duration: 273 },
{ file: "Aattakkari Maman Ponnu.mp3", details: "🎬 Thaarai Thappattai (2016) / 🎙️ M.M. Manasi, Prasanna / 🎼 Ilaiyaraaja / 📝 Ilaiyaraaja / 🎥 Bala", duration: 187 },
{ file: "Anbe Nee yenna.mp3", details: "🎬 Pandiyan (1992) / 🎙️ Mano, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 SP. Muthuraman", duration: 281 },
{ file: "Paandiyana Kokka.mp3", details: "🎬 Pandiyan (1992) / 🎙️ Mano / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 SP. Muthuraman", duration: 294 },
{ file: "Paandiyanin Rajayathil.mp3", details: "🎬 Pandiyan (1992) / 🎙️ Mano, K. S. Chithra / 🎼 Karthik Raja / 📝 Panchu Arunachalam / 🎥 S. P. Muthuraman", duration: 344 },
{ file: "Alli Alli.mp3", details: "🎬 Arunachalam (1997) / 🎙️ Mano, Swarnalatha / 🎼 Deva / 📝 Palani Bharathi / 🎥 Sundar C", duration: 303 },
{ file: "Athanda Ithanda.mp3", details: "🎬 Arunachalam (1997) / 🎙️ S. P. Balasubrahmanyam / 🎼 Deva / 📝 Vairamuthu / 🎥 Sundar C", duration: 337 },
{ file: "Mathadu Mathadu.mp3", details: "🎬 Arunachalam (1997) / 🎙️ S. P. Balasubrahmanyam, Sujatha Mohan, Meera, Manorama / 🎼 Deva / 📝 Palani Bharathi / 🎥 Sundar C", duration: 358 },
{ file: "Nagumo.mp3", details: "🎬 Arunachalam (1997) / 🎙️ Hariharan, K. S. Chithra / 🎼 Deva / 📝 Vairamuthu / 🎥 Sundar C", duration: 273 },
{ file: "Singam Ondru.mp3", details: "🎬 Arunachalam (1997) / 🎙️ Malaysia Vasudevan / 🎼 Deva / 📝 Vairamuthu / 🎥 Sundar C", duration: 285 },
{ file: "Kanni Koyil.mp3", details: "🎬 Vaanavil (2000) / 🎙️ S. P. Balasubrahmanyam / 🎼 Deva / 📝 Vairamuthu / 🎥 Manoj Kumar", duration: 199 },
{ file: "Velinattu Kaatru.mp3", details: "🎬 Vaanavil (2000) / 🎙️ Hariharan, Harini / 🎼 Deva / 📝 Vairamuthu / 🎥 Manoj Kumar", duration: 277 },
{ file: "Konja Naal Poru Thalaivaa.mp3", details: "🎬 Aasai (1995) / 🎙️ Hariharan / 🎼 Deva / 📝 Vaali / 🎥 Vasanth", duration: 314 },
{ file: "Meenamma Adikalayilum.mp3", details: "🎬 Aasai (1995) / 🎙️ P. Unnikrishnan, Anuradha Sriram / 🎼 Deva / 📝 Vaali / 🎥 Vasanth", duration: 336 },
{ file: "Pulveli Pulveli.mp3", details: "🎬 Aasai (1995) / 🎙️ K. S. Chithra, P. Unnikrishnan (humming) / 🎼 Deva / 📝 Vairamuthu / 🎥 Vasanth", duration: 391 },
{ file: "Shock Adikuthu.mp3", details: "🎬 Aasai (1995) / 🎙️ Suresh Peters, G. V. Prakash Kumar / 🎼 Deva / 📝 Vaali / 🎥 Vasanth", duration: 342 },
{ file: "Thiloththama.mp3", details: "🎬 Aasai (1995) / 🎙️ S. P. Balasubrahmanyam, Swarnalatha / 🎼 Deva / 📝 Vairamuthu / 🎥 Vasanth", duration: 347 },
{ file: "Innisai Paadi Varum F.mp3", details: "🎬 Thulladha Manamum Thullum (1999) / 🎙️ K. S. Chithra / 🎼 S. A. Rajkumar / 📝 Vairamuthu / 🎥 Ezhil", duration: 295 },
{ file: "Innisai Paadi Varum M.mp3", details: "🎬 Thulladha Manamum Thullum (1999) / 🎙️ P. Unnikrishnan / 🎼 S. A. Rajkumar / 📝 Vairamuthu / 🎥 Ezhil", duration: 295 },
{ file: "Irupathu Kodi Nillavukal.mp3", details: "🎬 Thulladha Manamum Thullum (1999) / 🎙️ Hariharan / 🎼 S. A. Rajkumar / 📝 Vairamuthu / 🎥 Ezhil", duration: 305 },
{ file: "Megamai Vanthu.mp3", details: "🎬 Thulladha Manamum Thullum (1999) / 🎙️ Rajesh Krishnan / 🎼 S. A. Rajkumar / 📝 Muthu Vijayan / 🎥 Ezhil", duration: 261 },
{ file: "Thodu Thodu Enave.mp3", details: "🎬 Thulladha Manamum Thullum (1999) / 🎙️ Hariharan, K. S. Chithra / 🎼 S. A. Rajkumar / 📝 Vairamuthu / 🎥 Ezhil", duration: 284 },
{ file: "Nee Paarthuttu Ponaalum.mp3", details: "🎬 Paarvai Ondre Pothume (2001) / 🎙️ Krishnaraj, Sumithra / 🎼 Bharani / 📝 Bharani / 🎥 Murali Krishna", duration: 250 },
{ file: "Thirudiya Idhayathai.mp3", details: "🎬 Paarvai Ondre Pothume (2001) / 🎙️ Harish Raghavendra, K. S. Chithra / 🎼 Bharani / 📝 Pa. Vijay / 🎥 Murali Krishna", duration: 289 },
{ file: "Thirumba Thirumba.mp3", details: "🎬 Paarvai Ondre Pothume (2001) / 🎙️ P. Unnikrishnan, Harini / 🎼 Bharani / 📝 Pa. Vijay / 🎥 Murali Krishna", duration: 315 },
{ file: "Thuli Thuliyaai Kottum.mp3", details: "🎬 Paarvai Ondre Pothume (2001) / 🎙️ Hariharan, Swarnalatha / 🎼 Bharani / 📝 Pa. Vijay / 🎥 Murali Krishna", duration: 365 },
{ file: "Yeh Asainthadum Katrukkum.mp3", details: "🎬 Paarvai Ondre Pothume (2001) / 🎙️ P. Unnikrishnan, S. Janaki / 🎼 Bharani / 📝 Pa. Vijay / 🎥 Murali Krishna", duration: 314 },
{ file: "Ootha Ootha.mp3", details: "🎬 Minsara Kanna (1999) / 🎙️ Hariharan, Harini / 🎼 Deva / 📝 Vaali / 🎥 K. S. Ravikumar", duration: 357 },
{ file: "Un Paer Solla.mp3", details: "🎬 Minsara Kanna (1999) / 🎙️ Hariharan, Sujatha Mohan / 🎼 Deva / 📝 Kalaikumar / 🎥 K. S. Ravikumar", duration: 310 },
{ file: "Aande Nootrande.mp3", details: "🎬 Mugavaree (2000) / 🎙️ Naveen / 🎼 Deva / 📝 Vairamuthu / 🎥 V. Z. Durai", duration: 437 },
{ file: "Hey Keechu Kiliye F.mp3", details: "🎬 Mugavaree (2000) / 🎙️ Harini, Chorus / 🎼 Deva / 📝 Vairamuthu / 🎥 V. Z. Durai", duration: 383 },
{ file: "Hey Keechu Kiliye M.mp3", details: "🎬 Mugavaree (2000) / 🎙️ Hariharan / 🎼 Deva / 📝 Vairamuthu / 🎥 V. Z. Durai", duration: 383 },
{ file: "Oh Nenje Nenje.mp3", details: "🎬 Mugavaree (2000) / 🎙️ Hariharan, Swarnalatha / 🎼 Deva / 📝 Vairamuthu / 🎥 V. Z. Durai", duration: 357 },
{ file: "Poo Virinchachu.mp3", details: "🎬 Mugavaree (2000) / 🎙️ P. Unnikrishnan, Anuradha Sriram / 🎼 Deva / 📝 Vairamuthu / 🎥 V. Z. Durai", duration: 351 },
{ file: "Yeh Nilave.mp3", details: "🎬 Mugavaree (2000) / 🎙️ Unni Menon / 🎼 Deva / 📝 Vairamuthu / 🎥 V. Z. Durai", duration: 255 },
{ file: "Naan Thamadikira.mp3", details: "🎬 Periyanna (1999) / 🎙️ Vijay / 🎼 Bharani / 📝 Bharani / 🎥 S. A. Chandrasekhar", duration: 260 },
{ file: "Nilave Nilave.mp3", details: "🎬 Periyanna (1999) / 🎙️ Hariharan, Sujatha Mohan / 🎼 Bharani / 📝 Vasan / 🎥 S. A. Chandrasekhar", duration: 304 },
{ file: "Pollachi Malay Rotula.mp3", details: "🎬 Periyanna (1999) / 🎙️ Malaysia Vasudevan, S. N. Surendar, Swarnalatha / 🎼 Bharani / 📝 Pulamaipithan / 🎥 S. A. Chandrasekhar", duration: 348 },
{ file: "Roadtula Oru.mp3", details: "🎬 Periyanna (1999) / 🎙️ Vijay / 🎼 Bharani / 📝 Bharani / 🎥 S. A. Chandrasekhar", duration: 252 },
{ file: "Thannane thamarapoo.mp3", details: "🎬 Periyanna (1999) / 🎙️ S. P. Balasubrahmanyam, K. S. Chithra / 🎼 Bharani / 📝 Arivumathi / 🎥 S. A. Chandrasekhar", duration: 276 },
{ file: "Chingucha Chingucha.mp3", details: "🎬 Porkkaalam (1997) / 🎙️ K. S. Chithra / 🎼 Deva / 📝 Vairamuthu / 🎥 Cheran / 🏷️ Sony Music Entertainment India Pvt. Ltd.", duration: 282 },
{ file: "Karuvella Kaatukkulae.mp3", details: "🎬 Porkkaalam (1997) / 🎙️ Arunmozhi, Sujatha Mohan, Anuradha Sriram / 🎼 Deva / 📝 Vairamuthu / 🎥 Cheran / 🏷️ Sony Music Entertainment India Pvt. Ltd.", duration: 331 },
{ file: "Oona Oonam.mp3", details: "🎬 Porkkaalam (1997) / 🎙️ Deva, Kovai Kamala / 🎼 Deva / 📝 Vairamuthu / 🎥 Cheran / 🏷️ Sony Music Entertainment India Pvt. Ltd.", duration: 292 },
{ file: "Thanjavooru Mannu Eduthu.mp3", details: "🎬 Porkkaalam (1997) / 🎙️ Krishnaraj / 🎼 Deva / 📝 Vairamuthu / 🎥 Cheran / 🏷️ Sony Music Entertainment India Pvt. Ltd.", duration: 325 },
{ file: "Iruvathu Vayathuvarai(Duet).mp3", details: "🎬 Kannodu Kanbathellam (1999) / 🎙️ Hariharan, S. Janaki / 🎼 Deva / 📝 Kalai Kumar / 🎥 Prabhu Solomon / 🏷️ Pyramid Music", duration: 349 },
{ file: "Thaj Mahal Ondru.mp3", details: "🎬 Kannodu Kanbathellam (1999) / 🎙️ Hariharan / 🎼 Deva / 📝 Mayil / 🎥 Prabhu Solomon / 🏷️ Pyramid Music", duration: 345 },
{ file: "CBI Enge Theda.mp3", details: "🎬 Poovellam Kettuppar (1999) / 🎙️ Sukhwinder Singh / 🎼 Yuvan Shankar Raja / 📝 Palani Bharathi / 🎥 Vasanth / 🏷️ Sa Re Ga Ma", duration: 364 },
{ file: "Chudithar Aninthu Vantha.mp3", details: "🎬 Poovellam Kettuppar (1999) / 🎙️ Hariharan, Sadhana Sargam / 🎼 Yuvan Shankar Raja / 📝 Palani Bharathi / 🎥 Vasanth / 🏷️ Sa Re Ga Ma", duration: 355 },
{ file: "Irava Pagala.mp3", details: "🎬 Poovellam Kettuppar (1999) / 🎙️ P. Unnikrishnan / 🎼 Yuvan Shankar Raja / 📝 Palani Bharathi / 🎥 Vasanth / 🏷️ Sa Re Ga Ma", duration: 312 },
{ file: "oh Senyoreeta.mp3", details: "🎬 Poovellam Kettuppar (1999) / 🎙️ P. Unnikrishnan / 🎼 Yuvan Shankar Raja / 📝 Palani Bharathi / 🎥 Vasanth / 🏷️ Sa Re Ga Ma", duration: 300 },
{ file: "Poova Poova Poove.mp3", details: "🎬 Poovellam Kettuppar (1999) / 🎙️ Nithyasree Mahadevan / 🎼 Yuvan Shankar Raja / 📝 Palani Bharathi / 🎥 Vasanth / 🏷️ Sa Re Ga Ma", duration: 355 },
{ file: "Poove Poove Male.mp3", details: "🎬 Poovellam Kettuppar (1999) / 🎙️ P. Unnikrishnan / 🎼 Yuvan Shankar Raja / 📝 Palani Bharathi / 🎥 Vasanth / 🏷️ Sa Re Ga Ma", duration: 353 },
{ file: "Aana Aavanna.mp3", details: "🎬 Panchalankurichi (1996) / 🎙️ Krishnaraj, Sujatha / 🎼 Deva / 📝 Vairamuthu / 🎥 Seeman / 🏷️ Pyramid Music", duration: 291 },
{ file: "Aathoram Thopukulae.mp3", details: "🎬 Panchalankurichi (1996) / 🎙️ Swarnalatha / 🎼 Deva / 📝 Vairamuthu / 🎥 Seeman / 🏷️ Pyramid Music", duration: 370 },
{ file: "Chinna Chinna Panithuli.mp3", details: "🎬 Panchalankurichi (1996) / 🎙️ K. S. Chithra / 🎼 Deva / 📝 Vairamuthu / 🎥 Seeman / 🏷️ Pyramid Music", duration: 305 },
{ file: "Othattora Sivappea.mp3", details: "🎬 Panchalankurichi (1996) / 🎙️ Hariharan, Anuradha Sriram / 🎼 Deva / 📝 Vairamuthu / 🎥 Seeman / 🏷️ Pyramid Music", duration: 357 },
{ file: "Vantiyala Vantiyala.mp3", details: "🎬 Panchalankurichi (1996) / 🎙️ Suresh Peters, Anuradha Sriram / 🎼 Deva / 📝 Seeman / 🎥 Seeman / 🏷️ Pyramid Music", duration: 311 },
{ file: "Mazhaiye Mazhaiye.mp3", details: "🎬 Eeram (2009) / 🎙️ Ranjith Govind / 🎼 Thaman S / 📝 Viveka / 🎥 Arivazhagan / 🏷️ Sony Music India", duration: 252 },
{ file: "Tharai Erangiya.mp3", details: "🎬 Eeram (2009) / 🎙️ Suchitra / 🎼 Thaman S / 📝 Viveka / 🎥 Arivazhagan / 🏷️ Sony Music Entertainment India Pvt. Ltd.", duration: 223 },
{ file: "Aatha Adikkaiyilae.mp3", details: "🎬 Thenmerku Paruvakaatru (2010) / 🎙️ Harini / 🎼 N. R. Raghunanthan / 📝 Vairamuthu / 🎥 Seenu Ramasamy", duration: 54 },
{ file: "Kalli Kallicheti.mp3", details: "🎬 Thenmerku Paruvakaatru (2010) / 🎙️ Shweta Mohan / 🎼 N. R. Raghunanthan / 📝 Vairamuthu / 🎥 Seenu Ramasamy", duration: 149 },
{ file: "Yedi Kallachi.mp3", details: "🎬 Thenmerku Paruvakaatru (2010) / 🎙️ Vijay Prakash, Shreya Ghoshal / 🎼 N. R. Raghunanthan / 📝 Vairamuthu / 🎥 Seenu Ramasamy", duration: 303 },
{ file: "Ooradangum Samathulae.mp3", details: "🎬 Kalavani (2010) / 🎙️ Senthilvelan / 🎼 S. S. Kumaran / 📝 Na. Muthukumar / 🎥 A. Sarkunam", duration: 232 },
{ file: "Orumurai Irumurai.mp3", details: "🎬 Kalavani (2010) / 🎙️ Harish Raghavendra, Srimathumitha / 🎼 S. S. Kumaran / 📝 Na. Muthukumar / 🎥 A. Sarkunam", duration: 225 },
{ file: "Peancha Mazhai.mp3", details: "🎬 Kalavani (2010) / 🎙️ A. Devendran / 🎼 S. S. Kumaran / 📝 Na. Muthukumar / 🎥 A. Sarkunam", duration: 96 },
{ file: "Sinthaiyiley.mp3", details: "🎬 Kalavani (2010) / 🎙️ Prasanna / 🎼 S. S. Kumaran / 📝 Na. Muthukumar / 🎥 A. Sarkunam", duration: 75 },
{ file: "Machaan Machaan.mp3", details: "🎬 Silambattam (2008) / 🎙️ Ilaiyaraaja, Bela Shende / 🎼 Yuvan Shankar Raja / 📝 Na. Muthukumar / 🎥 S. Saravanan", duration: 331 },
{ file: "Nalamdhana.mp3", details: "🎬 Silambattam (2008) / 🎙️ Silambarasan TR, Earl, Suzi Q, SUVI / 🎼 Yuvan Shankar Raja / 📝 Vaali, Gangai Amaran, Na. Muthukumar, Earl, Suzi Q, Silambarasan TR / 🎥 S. Saravanan", duration: 382 },
{ file: "Tamizhanna Naan Oru.mp3", details: "🎬 Silambattam (2008) / 🎙️ Shankar Mahadevan / 🎼 Yuvan Shankar Raja / 📝 Vaali / 🎥 S. Saravanan", duration: 308 },
{ file: "Vechikkava Remix.mp3", details: "🎬 Silambattam (2008) / 🎙️ Silambarasan Rajendar, Suchitra / 🎼 Yuvan Shankar Raja / 📝 Gangai Amaran / 🎥 S. Saravanan", duration: 286 },
{ file: "Where Is The Party.mp3", details: "🎬 Silambattam (2008) / 🎙️ Mukesh, Priyadharshini / 🎼 Yuvan Shankar Raja / 📝 Silambarasan Rajendar / 🎥 S. Saravanan", duration: 324 },
{ file: "Gaana Karunkuyile.mp3", details: "🎬 Sethu (1999) / 🎙️ Kovai Kamala / 🎼 Ilaiyaraaja / 📝 Ponnadiyan / 🎥 Bala", duration: 313 },
{ file: "Maalai En Vethanai.mp3", details: "🎬 Sethu (1999) / 🎙️ Unni Krishnan, Arunmozhi, S. N. Surendar / 🎼 Ilaiyaraaja / 📝 Arivumathi / 🎥 Bala", duration: 305 },
{ file: "Sikaadha Sitrondru.mp3", details: "🎬 Sethu (1999) / 🎙️ P. Unnikrishnan, Arunmozhi, S. N. Surendar / 🎼 Ilaiyaraaja / 📝 Palani Bharathi / 🎥 Bala", duration: 313 },
{ file: "Vidiya Vidiya.mp3", details: "🎬 Sethu (1999) / 🎙️ P. Unnikrishnan / 🎼 Ilaiyaraaja / 📝 Mu. Metha / 🎥 Bala", duration: 52 },
{ file: "Engengo sellum.mp3", details: "🎬 Pattakkathi Bhairavan (1979) / 🎙️ S. P. Balasubrahmanyam, S. Janaki / 🎼 Ilaiyaraaja / 🎥 V. B. Rajendra Prasad", duration: 270 },
{ file: "Azhagiya Nadhi Enna.mp3", details: "🎬 Paattukku Oru Thalaivan (1989) / 🎙️ S. P. Balasubrahmanyam, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Gangai Amaran / 🎥 Liaquat Ali Khan", duration: 269 },
{ file: "Kaathalae Kaathalae Duet.mp3", details: "🎬 96 (2018) / 🎙️ Chinmayi, Govind Vasantha / 🎼 Govind Vasantha / 📝 Karthik Netha / 🎥 C. Prem Kumar", duration: 194 },
{ file: "Kaathalae Kaathalae.mp3", details: "🎬 96 (2018) / 🎙️ Kalyani Menon, Chinmayi, Govind Vasantha / 🎼 Govind Vasantha / 📝 Karthik Netha / 🎥 C. Prem Kumar", duration: 193 },
{ file: "Kana Kangiren.mp3", details: "🎬 Aanandha Thaandavam (2009) / 🎙️ Shubha Mudgal, Nithyasree Mahadevan, Vinitra / 🎼 G. V. Prakash Kumar / 📝 Vairamuthu / 🎥 A. R. Gandhi Krishna", duration: 348 },
{ file: "Kodi Aruvi kottuthey.mp3", details: "🎬 Mehandi Circus (2019) / 🎙️ Pradeep Kumar, Nithyashree Venkataramanan / 🎼 Sean Roldan / 📝 Yugabharathi / 🎥 Saravana Rajendran", duration: 260 },
{ file: "The Life Of Ram.mp3", details: "🎬 96 (2018) / 🎙️ Pradeep Kumar / 🎼 Govind Vasantha / 📝 Karthik Netha / 🎥 C. Prem Kumar", duration: 354 },
{ file: "Vellattu Kannazhagi.mp3", details: "🎬 Mehandi Circus (2019) / 🎙️ Sean Roldan / 🎼 Sean Roldan / 📝 Yugabharathi / 🎥 Saravana Rajendran", duration: 234 },
{ file: "Ninaitthathu Yaro.mp3", details: "🎬 Paattukku Oru Thalaivan (1989) / 🎙️ Mano, S. Janaki / 🎼 Ilaiyaraaja / 📝 Gangai Amaran / 🎥 Liaquat Ali Khan", duration: 307 },
{ file: "Kadhal Vennila.mp3", details: "🎬 Vaanathaippola (2000) / 🎙️ Jayachandran / 🎼 S. A. Rajkumar / 📝 Ra. Ravishankar", duration: 235 },
{ file: "Mainave Mainave.mp3", details: "🎬 Vaanathaippola (2000) / 🎙️ Unni Menon, K. S. Chithra / 🎼 S. A. Rajkumar / 📝 Ra. Ravishankar", duration: 300 },
{ file: "Nadhiye Adi Nayil.mp3", details: "🎬 Vaanathaippola (2000) / 🎙️ Sukhwinder Singh, Anuradha Sriram / 🎼 S. A. Rajkumar / 📝 Pa. Vijay", duration: 253 },
{ file: "RojaPoo Malaiyilae.mp3", details: "🎬 Vaanathaippola (2000) / 🎙️ K. S. Chithra, Mano / 🎼 S. A. Rajkumar / 📝 Pa. Vijay", duration: 288 },
{ file: "Thavaniye Ennai.mp3", details: "🎬 Vaanathaippola (2000) / 🎙️ S. P. Balasubrahmanyam, Swarnalatha / 🎼 S. A. Rajkumar / 📝 Pa. Vijay", duration: 258 },
{ file: "Yengal Veetil.mp3", details: "🎬 Vaanathaippola (2000) / 🎙️ S. P. Balasubrahmanyam, Sujatha, Arunmozhi / 🎼 S. A. Rajkumar / 📝 Na. Muthukumar, Pa. Vijay", duration: 266 },
{ file: "Dhavanipotta Deepavali.mp3", details: "🎬 Sandakozhi (2005) / 🎙️ Vijay Yesudas, Shreya Ghoshal / 🎼 Yuvan Shankar Raja / 📝 Yugabharathi", duration: 263 },
{ file: "Kaadhal Neethana.mp3", details: "🎬 Time (1999) / 🎙️ P. Unnikrishnan, Sujatha Mohan / 🎼 Ilaiyaraaja / 📝 Palani Bharathi", duration: 302 },
{ file: "Ketta Kodukkira Boomi.mp3", details: "🎬 Sandakozhi (2005) / 🎙️ Jassie Gift, Sujatha Mohan, Chinmayi Sripaada, Ganga / 🎼 Yuvan Shankar Raja / 📝 Thamarai", duration: 266 },
{ file: "Muthu Nilavae.mp3", details: "🎬 Time (1999) / 🎙️ Karthik Raja, Gopika Poornima / 🎼 Ilaiyaraaja / 📝 Palani Bharathi", duration: 350 },
{ file: "Thavikiren.mp3", details: "🎬 Time (1999) / 🎙️ Hariharan, Bhavatharini / 🎼 Ilaiyaraaja / 📝 Palani Bharathi", duration: 312 },
{ file: "Cho Larey.mp3", details: "🎬 Ullaasam (1997) / 🎙️ S. P. Balasubrahmanyam, Harini, Venkat Prabhu / 🎼 Karthik Raja / 📝 Paarthi Bhaskar", duration: 295 },
{ file: "Konjum Manjal.mp3", details: "🎬 Ullaasam (1997) / 🎙️ Hariharan, Harini / 🎼 Karthik Raja / 📝 Palani Bharathi", duration: 334 },
{ file: "Muthae Muthamma.mp3", details: "🎬 Ullaasam (1997) / 🎙️ Kamal Haasan, Bhavatharini, Swarnalatha / 🎼 Karthik Raja / 📝 Palani Bharathi", duration: 304 },
{ file: "Veesum Kaatrukku.mp3", details: "🎬 Ullaasam (1997) / 🎙️ P. Unnikrishnan, Harini / 🎼 Karthik Raja / 📝 Palani Bharathi", duration: 299 },
{ file: "Yaaro Yaar Yaaro.mp3", details: "🎬 Ullaasam (1997) / 🎙️ Ilaiyaraaja, Bhavatharini / 🎼 Karthik Raja / 📝 Arivumathi", duration: 154 },
{ file: "Aalaala Kandaa.mp3", details: "🎬 Sangamam (1999) / 🎙️ Hariharan, M. S. Viswanathan / 🎼 A. R. Rahman / 📝 Vairamuthu", duration: 138 },
{ file: "Margazhi Thingal.mp3", details: "🎬 Sangamam (1999) / 🎙️ P. Unnikrishnan, S. Janaki, A. R. Rahman, Srimathumitha / 🎼 A. R. Rahman / 📝 Vairamuthu", duration: 416 },
{ file: "Mazhaithuli Mazhaithuli.mp3", details: "🎬 Sangamam (1999) / 🎙️ Hariharan, M. S. Viswanathan / 🎼 A. R. Rahman / 📝 Vairamuthu", duration: 411 },
{ file: "Mudhal Murai.mp3", details: "🎬 Sangamam (1999) / 🎙️ Srinivas, Sujatha Mohan / 🎼 A. R. Rahman / 📝 Vairamuthu", duration: 370 },
{ file: "Sowkiyama Kanne.mp3", details: "🎬 Sangamam (1999) / 🎙️ Nithyasree Mahadevan / 🎼 A. R. Rahman / 📝 Vairamuthu", duration: 354 },
{ file: "Varaha Nadikkarai Oram.mp3", details: "🎬 Sangamam (1999) / 🎙️ Shankar Mahadevan / 🎼 A. R. Rahman / 📝 Vairamuthu", duration: 378 },
{ file: "En Nenjee.mp3", details: "🎬 Vamsam (2010) / 🎙️ Ananthu, Priyadharshini / 🎼 Taj Noor / 📝 Na. Muthukumar", duration: 295 },
{ file: "Kompula Poove Suthi.mp3", details: "🎬 Virumaandi (2004) / 🎙️ Kamal Haasan / 🎼 Ilaiyaraaja / 📝 Kamal Haasan", duration: 301 },

{ file: "Maruthani Poova Pola.mp3", details: "🎬 Vamsam (2010) / 🎙️ Mukesh, Surmukhi / 🎼 Taj Noor / 📝 Na. Muthukumar", duration: 297 },
{ file: "Unnaivida.mp3", details: "🎬 Virumaandi (2004) / 🎙️ Kamal Haasan, Shreya Ghoshal / 🎼 Ilaiyaraaja / 📝 Kamal Haasan", duration: 385 },
{ file: "katthavaraya.mp3", details: "🎬 Kavithai (1976) / 🎙️ Malathi,  Sabesh / 🎼 Deva", duration: 271 },
{ file: "Kotha Raja.mp3", details: "🎬 King of Kotha (2023) / 🎙️ Asal Kolaar, Dabzee, Roll Rida, Resmi Sateesh / 🎼 Jakes Bejoy / 📝 Mu.Ri", duration: 273 },
{ file: "Oru Kola Kili.mp3", details: "🎬 Uzhaippali (1993) / 🎙️ S. P. Balasubrahmanyam / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 299 },
{ file: "Oru Maina.mp3", details: "🎬 Uzhaippali (1993) / 🎙️ Mano, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 309 },
{ file: "Umma Ummamaa.mp3", details: "🎬 Adithadi (2004) / 🎙️ Malathi, Manikka Vinayagam / 🎼 Deva", duration: 273 },
{ file: "Uzhaippali illatha.mp3", details: "🎬 Uzhaippali (1993) / 🎙️ Mano / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 308 },
{ file: "Annan Adhiradi.mp3", details: "🎬 Leo Promo Track (2023) / 🎙️ Tha Mystro, MC SAI / 🎼 MJ Melodies / 📝 Tha Mystro, MC SAI / 🎥 Saanmuu", duration: 177 },
{ file: "Hey Saloma.mp3", details: "🎬 Subash (1996) / 🎙️ Vidyasagar, Swarnalatha / 🎼 Vidyasagar / 📝 R. V. Udayakumar", duration: 320 },
{ file: "Sudum Nilavu.mp3", details: "🎬 Thambi (2006) / 🎙️ P. Unnikrishnan, Harini / 🎼 Vidyasagar / 📝 Vairamuthu", duration: 255 },
{ file: "Summa Kidantha.mp3", details: "🎬 Thambi (2006) / 🎙️ Karthik, Kalyani Nair / 🎼 Vidyasagar / 📝 Vairamuthu", duration: 320 },
{ file: "Balle Lakka.mp3", details: "🎬 Mankatha (2011) / 🎙️ Karthik, Vijay Yesudas, Anusha Dhayanidhi / 🎼 Yuvan Shankar Raja / 📝 Vaali", duration: 315 },
{ file: "January Madham.mp3", details: "🎬 7G Rainbow Colony (2004) / 🎙️ Mathangi Jagdish, Kunal Ganjawala / 🎼 Yuvan Shankar Raja / 📝 Na. Muthukumar", duration: 314 },
{ file: "Machi Open The Bottle.mp3", details: "🎬 Mankatha (2011) / 🎙️ Mano, Haricharan, Tippu, Naveen Madhav / 🎼 Yuvan Shankar Raja / 📝 Vaali", duration: 286 },
{ file: "Mangatha Extended Dance.mp3", details: "🎬 Mankatha (2011) / 🎙️ Yuvan Shankar Raja, Ranjith, Premgi Amaren, Sucharita, Anitha / 🎼 Yuvan Shankar Raja / 📝 Gangai Amaren, Sucharita, Yuvan Shankar Raja", duration: 365 },
{ file: "Vaada Bin Laada.mp3", details: "🎬 Mankatha (2011) / 🎙️ Krish, Suchitra / 🎼 Yuvan Shankar Raja / 📝 Vaali", duration: 269 },
{ file: "Vilayadu Mangatha.mp3", details: "🎬 Mankatha (2011) / 🎙️ Yuvan Shankar Raja, Ranjith, Premgi Amaren, Sucharita, Anitha / 🎼 Yuvan Shankar Raja / 📝 Gangai Amaren, Sucharita, Yuvan Shankar Raja", duration: 363 },
{ file: "Asku Maaro.mp3", details: "💽 Independent Single (2021) / 🎙️ Dharan Kumar, Sivaangi Krishnakumar / 🎼 Dharan Kumar / 📝 Dharan Kumar", duration: 240 },
{ file: "Bae.mp3", details: "🎬 Don (2022) / 🎙️ Adithya RK / 🎼 Anirudh Ravichander / 📝 Vignesh Shivan", duration: 243 },
{ file: "Jalabulajangu.mp3", details: "🎬 Don (2022) / 🎙️ Anirudh Ravichander / 🎼 Anirudh Ravichander / 📝 Rokesh", duration: 203 },
{ file: "Private Party.mp3", details: "🎬 Don (2022) / 🎙️ Anirudh Ravichander, Jonita Gandhi / 🎼 Anirudh Ravichander / 📝 Sivakarthikeyan", duration: 217 },
{ file: "Anaarkali.mp3", details: "🎬 Varushamellam Vasantham (2002) / 🎙️ P. Unnikrishnan, Ganga Sitharasu / 🎼 Sirpy / 📝 Ra. Ravishankar", duration: 316 },
{ file: "Enge andha vennila.mp3", details: "🎬 Varushamellam Vasantham (2002) / 🎙️ Unni Menon / 🎼 Sirpy / 📝 Ra. Ravishankar", duration: 301 },
{ file: "Enge Antha Vennila Female.mp3", details: "🎬 Varushamellam Vasantham (2002) / 🎙️ Sujatha Mohan / 🎼 Sirpy / 📝 Ra. Ravishankar", duration: 304 },
{ file: "Muthal muthalai unai.mp3", details: "🎬 Varushamellam Vasantham (2002) / 🎙️ P. Unnikrishnan, Sujatha Mohan / 🎼 Sirpy / 📝 Ra. Ravishankar", duration: 288 },
{ file: "Naan ready Neenga.mp3", details: "🎬 Varushamellam Vasantham (2002) / 🎙️ Krishnaraj, K. S. Chithra / 🎼 Sirpy / 📝 Manavai Ponmanikkam", duration: 264 },
{ file: "Erukanchedi ooram.mp3", details: "🎬 Santhaikku Vantha Kili (1995) / 🎙️ S. Janaki / 🎼 Deva / 📝 Vaali", duration: 281 },
{ file: "oothikka mama.mp3", details: "🎬 Santhaikku Vantha Kili (1995) / 🎙️ S. Janaki / 🎼 Deva / 📝 Vaali", duration: 282 },
{ file: "Poththu Athai.mp3", details: "🎬 Kadhal Kirukkan (2003) / 🎙️ Manikka Vinayagam, Malathy / 🎼 Deva / 📝 Deva Kumar", duration: 299 },

{ file: "Poove Muthal Poove.mp3", details: "🎬 Kadhal Kirukkan (2003) / 🎙️ Harish Raghavendra / 🎼 Deva / 📝 Kabilan", duration: 276 },
{ file: "Poove Mudhal poove female.mp3", details: "🎬 Kadhal Kirukkan (2003) / 🎙️ Chinmayi Sripada / 🎼 Deva / 📝 Kabilan", duration: 276 },
{ file: "Aattama TherottamaMix.mp3", details: "🎬 Singakutty (2008) / 🎙️ Anuradha Sriram, DJ Ewan / 🎼 Prasanna Shekhar / 📝 Vaali", duration: 273 },
{ file: "Aalana Naal Mudhala.mp3", details: "🎬 Kaadhal Kavithai (1998) / 🎙️ Pushpavanam Kuppusamy, Sowmya Raoh / 🎼 Ilaiyaraaja / 📝 Agathiyan", duration: 308 },
{ file: "Thath Thom thakdheemi.mp3", details: "🎬 Kaadhal Kavithai (1998) / 🎙️ Ila Arun, Swarnalatha / 🎼 Ilaiyaraaja / 📝 Agathiyan", duration: 292 },
{ file: "Oru Naalil Dream Mix.mp3", details: "🎬 Pudhupettai (2006) / 🎙️ Yuvan Shankar Raja / 🎼 Yuvan Shankar Raja / 📝 Na. Muthukumar", duration: 323 },
{ file: "Oru Naalil.mp3", details: "🎬 Pudhupettai (2006) / 🎙️ Yuvan Shankar Raja / 🎼 Yuvan Shankar Raja / 📝 Na. Muthukumar", duration: 385 },
{ file: "Pulpesum Poo Pesum.mp3", details: "🎬 Pudhupettai (2006) / 🎙️ Vijay Yesudas, Tanvi Shah, Premji Amaran, Yuvan Shankar Raja / 🎼 Yuvan Shankar Raja / 📝 Na. Muthukumar", duration: 326 },
{ file: "Appan Panna Thappula.mp3", details: "🎬 Thirupaachi (2005) / 🎙️ Pushpavanam Kuppusamy, Anuradha Sriram / 🎼 Dhina / 📝 Perarasu", duration: 288 },
{ file: "Kannum Kannumthan.mp3", details: "🎬 Thirupaachi (2005) / 🎙️ Harish Raghavendra, Uma Ramanan, Premji Amaren / 🎼 Mani Sharma / 📝 Perarasu", duration: 354 },
{ file: "Kattu Kattu.mp3", details: "🎬 Thirupaachi (2005) / 🎙️ Manikka Vinayagam, Sumangali / 🎼 Devi Sri Prasad / 📝 Perarasu", duration: 311 },
{ file: "Kumbida Pona deivam.mp3", details: "🎬 Thirupaachi (2005) / 🎙️ Shankar Mahadevan, Malathy Lakshman / 🎼 Dhina / 📝 Perarasu", duration: 252 },
{ file: "Nee Entha Ooru.mp3", details: "🎬 Thirupaachi (2005) / 🎙️ Tippu / 🎼 Dhina / 📝 Perarasu", duration: 287 },
{ file: "Adho Varaa.mp3", details: "🎬 Sullan (2004) / 🎙️ Pushpavanam Kuppusamy, Harini / 🎼 Vidyasagar / 📝 Pa. Vijay", duration: 254 },
{ file: "Thottu Thottu.mp3", details: "🎬 Ethirum Puthirum (1999) / 🎙️ Swarnalatha, Pushpavanam Kuppusamy / 🎼 Vidyasagar / 📝 Vairamuthu", duration: 285 },
{ file: "Kaathu Pasapasanga.mp3", details: "🎬 Ethirum Puthirum (1999) / 🎙️ Pushpavanam Kuppusamy, Malaysia Vasudevan, Anuradha Sriram, Gopal Rao / 🎼 Vidyasagar / 📝 Vairamuthu", duration: 306 },
{ file: "Potteduthu vachuvidava.mp3", details: "🎬 Style (2002) / 🎙️ Pushpavanam Kuppusamy, Swarnalatha / 🎼 Bharani / 📝 Pa. Vijay", duration: 231 },
{ file: "Thom Thom.mp3", details: "🎬 Alli Thandha Vaanam (2001) / 🎙️ Hariharan, K. S. Chithra / 🎼 Vidyasagar", duration: 299 },
{ file: "Vadi Vadi Nattukkattai.mp3", details: "🎬 Alli Thandha Vaanam (2001) / 🎙️ Shankar Mahadevan, Sujatha Mohan / 🎼 Vidyasagar", duration: 268 },
{ file: "Bothai yeri pochu.mp3", details: "🎬 Jai Hind (1994) / 🎙️ S. P. Sailaja, Suresh Peters / 🎼 Vidyasagar / 📝 Vairamuthu", duration: 268 },

{ file: "Kanna En Selaikulla.mp3", details: "🎬 Jai Hind (1994) / 🎙️ S. P. Balasubrahmanyam, S. Janaki / 🎼 Vidyasagar / 📝 Vairamuthu", duration: 293 },
{ file: "Mutham thara.mp3", details: "🎬 Jai Hind (1994) / 🎙️ Mano, Sindhu / 🎼 Vidyasagar / 📝 Vairamuthu", duration: 211 },
{ file: "Thanni Vachu.mp3", details: "🎬 Jai Hind (1994) / 🎙️ Arjun, Malgudi Shubha, Vidyasagar / 🎼 Vidyasagar / 📝 Vairamuthu", duration: 286 },
{ file: "Katchi Sera.mp3", details: "💿 Think Indie (2024) / 🎙️ Sai Abhyankar / 🎼 Sai Abhyankar / 📝 Adesh Krishna", duration: 182 },
{ file: "Ordinary Person.mp3", details: "🎬 Leo (2023) / 🎙️ Anirudh Ravichander, Nikhita Gandhi / 🎼 Anirudh Ravichander / 📝 Heisenberg", duration: 138 },
{ file: "Kannathil Kannam.mp3", details: "🎬 Watchman Vadivel (1994) / 🎙️ S. P. Balasubrahmanyam, K. S. Chithra / 🎼 Deva / 📝 Vaali", duration: 282 },
{ file: "Chandiranum Sooriyanum.mp3", details: "🎬 Watchman Vadivel (1994) / 🎙️ S. P. Balasubrahmanyam, K. S. Chithra / 🎼 Deva / 📝 Vaali", duration: 277 },
{ file: "Kissik.mp3", details: "🎬 Pushpa 2: The Rule (2024) / 🎙️ Sreeleela / 🎼 Devi Sri Prasad / 📝 Chandrabose", duration: 247 },
{ file: "Pushpa Pushpa.mp3", details: "🎬 Pushpa 2: The Rule (2024) / 🎙️ Nakash Aziz / 🎼 Devi Sri Prasad / 📝 Chandrabose", duration: 256 },
{ file: "Aagaya Vennilavae.mp3", details: "🎬 Arangetra Velai (1990) / 🎙️ K. J. Yesudas, Uma Ramanan / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 279 },
{ file: "Pattu Poove.mp3", details: "🎬 Sembaruthi (1992) / 🎙️ S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 307 },
{ file: "Nila Kayum Neram.mp3", details: "🎬 Sembaruthi (1992) / 🎙️ Mano, S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 303 },
{ file: "Nadanthaal.mp3", details: "🎬 Sembaruthi (1992) / 🎙️ S. P. Balasubrahmanyam / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 305 },
{ file: "Kadalile Thanimayil.mp3", details: "🎬 Sembaruthi (1992) / 🎙️ Nagoor Haniffa, Mano / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 307 },
{ file: "Kadalile Ezhumpura.mp3", details: "🎬 Sembaruthi (1992) / 🎙️ Ilaiyaraaja / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 301 },
{ file: "Chemparuthi Poovu.mp3", details: "🎬 Sembaruthi (1992) / 🎙️ Mano, K. S. Chithra, Dr. Bhanumathi / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 347 },
{ file: "Chalakku Chalakku Selai.mp3", details: "🎬 Sembaruthi (1992) / 🎙️ Mano, S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 279 },
{ file: "Boom shakala.mp3", details: "🎬 Kulir 100 Degrees (2015) / 🎙️ Bobo Shashi, Benny Dayal, Abishek & Nrithya / 🎼 Bobo Shashi / 📝 Pa. Vijay", duration: 263 },
{ file: "Ayyayo Nenju.mp3", details: "🎬 Aadukalam (2011) / 🎙️ G. V. Prakash Kumar, S. P. Balasubrahmanyam, S. P. B. Charan, Prashanthini / 🎼 G. V. Prakash Kumar / 📝 Snehan", duration: 324 },
{ file: "Otha Sollaala.mp3", details: "🎬 Aadukalam (2011) / 🎙️ G. V. Prakash Kumar, Velmurugan / 🎼 G. V. Prakash Kumar / 📝 Snehan", duration: 239 },
{ file: "Yathe Yathe.mp3", details: "🎬 Aadukalam (2011) / 🎙️ G. V. Prakash Kumar / 🎼 G. V. Prakash Kumar / 📝 Snehan", duration: 346 },
{ file: "Ponnu Oruthi Summa.mp3", details: "🎬 Charlie Chaplin (2002) / 🎙️ S. P. Balasubrahmanyam, Harish Ragavendra / 🎼 Bharani / 📝 Palani Bharathi", duration: 305 },
{ file: "Ava Kanna Partha.mp3", details: "🎬 Charlie Chaplin (2002) / 🎙️ S. P. Balasubrahmanyam, Harish Ragavendra / 🎼 Bharani / 📝 Palani Bharathi", duration: 302 },
{ file: "Muthalam Santhipil.mp3", details: "🎬 Charlie Chaplin (2002) / 🎙️ Swarnalatha, Unni Krishnan / 🎼 Bharani / 📝 Palani Bharathi", duration: 302 },
{ file: "Unthan Vizhi Munai.mp3", details: "🎬 4 Students (2004) / 🎙️ Jassie Gift, Jyotsna / 🎼 Jassie Gift / 📝 Palani Bharathi", duration: 285 },
{ file: "Lajjavathiyea.mp3", details: "🎬 4 Students (2004) / 🎙️ Jassie Gift / 🎼 Jassie Gift / 📝 Palani Bharathi", duration: 276 },
{ file: "Lajjavathiyea II.mp3", details: "🎬 4 Students (2004) / 🎙️ Jassie Gift / 🎼 Jassie Gift / 📝 Palani Bharathi", duration: 276 },
{ file: "Annakili II.mp3", details: "🎬 4 Students (2004) / 🎙️ Prasanna chorus / 🎼 Jassie Gift / 📝 Palani Bharathi", duration: 260 },
{ file: "Annakili.mp3", details: "🎬 4 Students (2004) / 🎙️ Jassie Gift / 🎼 Jassie Gift / 📝 Kaithapram", duration: 262 },
{ file: "Padagottum Pattamma.mp3", details: "🎬 Chinnavar (2020) / 🎙️ Malaysia Vasudevan, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Gangai Amaran", duration: 306 },

{ file: "Maaraappu Chela.mp3", details: "🎬 Chinnavar (2020) / 🎙️ Mano, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Gangai Amaran", duration: 299 },
{ file: "Kottukkili.mp3", details: "🎬 Chinnavar (2020) / 🎙️ K. S. Chithra, S. P. Balasubrahmanyam / 🎼 Ilaiyaraaja / 📝 Gangai Amaran", duration: 307 },
{ file: "Gunturu Gongura.mp3", details: "🎬 Chinnavar (2020) / 🎙️ Mano, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Gangai Amaran", duration: 304 },
{ file: "Andhiyiley Vaanam.mp3", details: "🎬 Chinnavar (2020) / 🎙️ Mano, Swarnalatha / 🎼 Ilayaraja / 📝 Gangai Amaran", duration: 295 },
{ file: "Kadavullum Neeyam.mp3", details: "🎬 Sindhu Nathi Poo (1994) / 🎙️ Unni Menon, S. Janaki / 🎼 Soundaryan / 📝 Vairamuthu", duration: 312 },
{ file: "Adiye Adi Chinnapulla.mp3", details: "🎬 Sindhu Nathi Poo (1994) / 🎙️ Mano, S. Janaki / 🎼 Soundaryan / 📝 Vairamuthu", duration: 292 },
{ file: "Mathalam Kottudhadi.mp3", details: "🎬 Sindhu Nathi Poo (1994) / 🎙️ S. P. Balasubrahmanyam, Swarnalatha, Loose Mohan / 🎼 Soundaryan / 📝 Vairamuthu", duration: 295 },
{ file: "Aathadi Enna Odambu.mp3", details: "🎬 Sindhu Nathi Poo (1994) / 🎙️ Shahul Hameed / 🎼 Soundaryan / 📝 Vairamuthu", duration: 272 },
{ file: "Aathi Vadayile.mp3", details: "🎬 Sindhu Nathi Poo (1994) / 🎙️ K. J. Yesudas / 🎼 Soundaryan / 📝 Vairamuthu", duration: 306 },
{ file: "Poi Vaada.mp3", details: "🎬 Dharmadurai (2016) / 🎙️ Srimathumitha / 🎼 Yuvan Shankar Raja / 📝 Vairamuthu", duration: 124 },
{ file: "Endha Pakkam.mp3", details: "🎬 Dharmadurai (2016) / 🎙️ Rahul Nambiar, Chinmayi Sripada / 🎼 Yuvan Shankar Raja / 📝 Vairamuthu", duration: 303 },
{ file: "Makka Kalanguthappa.mp3", details: "🎬 Dharmadurai (2016) / 🎙️ Mathichiyam Bala / 🎼 Yuvan Shankar Raja / 📝 Mathichiyam Bala", duration: 246 },
{ file: "Aandipatti.mp3", details: "🎬 Dharmadurai (2016) / 🎙️ Senthil Dass, Surmukhi / 🎼 Yuvan Shankar Raja / 📝 Vairamuthu", duration: 279 },
{ file: "Adi Raakkumuthu.mp3", details: "🎬 Ejamaan (1993) / 🎙️ S.P. Balasubrahmanyam / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 310 },
{ file: "Ulagam Piranthathu.mp3", details: "🎬 Paasam (1962) / 🎤 T. M. Soundararajan / 🎼 Viswanathan - Ramamoorthy / 📝 Kannadasan", duration: 226 },
{ file: "Nilave Mugam.mp3", details: "🎬 Ejamaan (1993) / 🎙️ S. P. Balasubrahmanyam, S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 307 },
{ file: "Oru Naalum Unai.mp3", details: "🎬 Ejamaan (1993) / 🎙️ S. P. Balasubrahmanyam, S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 359 },
{ file: "Urakka Kaththu.mp3", details: "🎬 Ejamaan (1993) / 🎙️ S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 304 },
{ file: "Poothathu_Poonthoppu.mp3", details: "🎬 Thanga Manasukkaran / 1992 /🎙️  Mano, S.Janaki /🎼  Ilaiyaraaja / 📝 Piraisoodan, Kamakodiyan, GangaiAmaran", duration: 289 },
{ file: "Aalappol_Velapol.mp3", details: "🎬 Ejamaan (1993) / 🎤 S.P. Balasubrahmanyam, Chithra / 🎼 Ilaiyaraaja / 📝 Vaali", duration: 305 },
{ file: "Peelings.mp3", details: "🎬 Pushpa 2 - The Rule ( Tamil) / 2024 /🎙️ Senthil Ganesh, Rajalakshmi /🎼 Devi Sri Prasad / 📝 Viveka, Siju Thuravoor", duration: 247 },
{ file: "Nee_Pottu_Vacha.mp3", details: "🎬 Ponmana Selvan (1989) / 🎤 Malaysia Vasudevan, Mano, K.S. Chithra / 🎼 Ilaiyaraaja / 📝 Gangai Amaran", duration: 266 },
{ file: "Naa_Ready.mp3", details: "🎬 Leo (2023) / 🎤 Thalapathy Vijay, Anirudh Ravichander / 🎼 Anirudh Ravichander / 📝 Vishnu Edavan", duration: 254 },
{ file: "Hey_Minnale.mp3", details: "🎬 Amaran (2024) / 🎤 Haricharan, Shweta Mohan / 🎼 G.V Prakash Kumar / 📝 Karthik Netha", duration: 230 },
{ file: "Achacho.mp3", details: "🎬 Aranmanai 4 (2024) / 🎤 Kharesma Ravichandran, Srinisha Jayaseelan, Hiphop Tamizha / 🎼 Hiphop Tamizha / 📝 Vignesh Srikanth", duration: 193 },
{ file: "Edho Solla.mp3", details: "🎬 Murungakkai Chips (2020) / 🎤 Sid Sriram / 🎼 Dharan Kumar / 📝 Ravindhar Chandrasekaran", duration: 303 },
{ file: "Chillanjirukkiye.mp3", details: "🎬 Lubber Pandhu (2024) / 🎤 Pradeep Kumar, Shivangi / 🎼 Sean Roldan / 📝 Mohan Rajan", duration: 247 }

]
  },

  {
    base: "https://github.com/atsuperman/PLAY/raw/main/",
    songs: [
{ file: "Beer_song_Pacha_Kuthikennen.mp3", details: "🎬 Diesel (2024) / 🎤 Gana Guna, Dhibu Ninan Thomas, Maniratnam, Kapil Kapilan / 🎼 Dhibu Ninan Thomas / 📝 Rokesh", duration: 196 },
{ file: "Kaattumalli.mp3", details: "🎬 Viduthalai Part 1 (2023) / 🎤 Ilaiyaraaja, Ananya Bhat / 🎼 Ilaiyaraaja / 📝 Ilaiyaraaja", duration: 307 }

 ]
  },

{
    base: "https://github.com/atsuperman/G1/raw/refs/heads/main/",
    songs: [
{ file: "Engalukkum Kaalam.m4a", details: "🎬 Pasamalar (1961) / 🎙️ T M Soundararajan, P Susheela / 🎼 Viswanathan–Ramamoorthy / 📝 Kannadasan", duration: 219 },
{ file: "Malargalaipol.m4a", details: "🎬 Pasamalar (1961) / 🎙️ T M Soundararajan / 🎼 Viswanathan–Ramamoorthy / 📝 Kannadasan", duration: 292 },
{ file: "Mayangugiraal Oru.m4a", details: "🎬 Pasamalar (1961) / 🎙️ P Susheela / 🎼 Viswanathan–Ramamoorthy / 📝 Kannadasan", duration: 245 },
{ file: "Malarndhum Malaradha.m4a", details: "🎬 Pasamalar (1961) / 🎙️ T M Soundararajan, P Susheela / 🎼 Viswanathan–Ramamoorthy / 📝 Kannadasan", duration: 309 },
{ file: "Paattondru Ketten.m4a", details: "🎬 Pasamalar (1961) / 🎙️ Jamuna Rani / 🎼 Viswanathan–Ramamoorthy / 📝 Kannadasan", duration: 273 },
{ file: "Vaarai En Thozhi.m4a", details: "🎬 Pasamalar (1961) / 🎙️ L R Eswari / 🎼 Viswanathan–Ramamoorthy / 📝 Kannadasan", duration: 310 },
{ file: "Yaar Yaar Yaar Aval.m4a", details: "🎬 Pasamalar (1961) / 🎙️ P B Sreenivas, P Susheela / 🎼 Viswanathan–Ramamoorthy / 📝 Kannadasan", duration: 262 },
{ file: "Aadaamal Aadukiren.m4a", details: "🎬 Aayirathil Oruvan (1965) / 🎙️ P Susheela / 🎼 Viswanathan – Ramamoorthy / 📝 Vaali", duration: 249 },
{ file: "Odum Megangalae.m4a", details: "🎬 Aayirathil Oruvan (1965) / 🎙️ T M Soundararajan / 🎼 Viswanathan–Ramamoorthy / 📝 Kannadasan", duration: 267 },
{ file: "Atho Andha.m4a", details: "🎬 Aayirathil Oruvan (1965) / 🎙️ T M Soundararajan / 🎼 Viswanathan–Ramamoorthy / 📝 Kannadasan", duration: 305 },
{ file: "Unnai Naan.m4a", details: "🎬 Aayirathil Oruvan (1965) / 🎙️ P Susheela / 🎼 Viswanathan–Ramamoorthy / 📝 Vaali", duration: 204 },
{ file: "Yen Endra Kelvi.m4a", details: "🎬 Aayirathil Oruvan (1965) / 🎙️ T M Soundararajan / 🎼 M S Viswanathan‑Ramamoorthy / 📝 Vaali", duration: 222 },
{ file: "Naanamo.m4a", details: "🎬 Aayirathil Oruvan (1965) / 🎙️ T. M. Soundararajan, P. Susheela / 🎼 Viswanathan Ramamoorthy / 📝 Kannadasan", duration: 281 }
]
  },

  {
    base: "https://github.com/atsuperman/play2/raw/main/",
    songs: [
{ file: "Paal Vannam.mp3", details: "🎬 Paasam (1962) / 🎤 P. B. Srinivas, P. Susheela / 🎼 Viswanathan - Ramamoorthy", duration: 248 },
{ file: "Kavalaiyai Theerpadhu Naatiya.mp3", details: "🎬 Sivakavi (1943) / 🎙️ M. K. Thyagaraja Bhagavathar / 🎼 Papanasam Sivan / 📝 Papanasam Sivan", duration: 176 },
{ file: "Soppana Vaazhvil.mp3", details: "🎬 Sivakavi (1943) / 🎙️ M. K. Thyagaraja Bhagavathar / 🎼 Papanasam Sivan / 📝 Papanasam Sivan", duration: 150 },
{ file: "Vadhaname Chandra Bimbamo.mp3", details: "🎬 Sivakavi (1943) / 🎙️ M. K. Thyagaraja Bhagavathar / 🎼 Papanasam Sivan / 📝 Papanasam Sivan", duration: 167 },
{ file: "Vallalai Paadum Vaayal.mp3", details: "🎬 Sivakavi (1943) / 🎙️ M. K. Thyagaraja Bhagavathar / 🎼 Papanasam Sivan", duration: 188 },
{ file: "Vasantha Ruthu.mp3", details: "🎬 Sivakavi (1943) / 🎙️ M. K. Thyagaraja Bhagavathar, S. Jayalakshmi / 🎼 Papanasam Sivan / 📝 Papanasam Sivan", duration: 156 }
 ]
  },
  
  {
    base: "https://github.com/atsuperman/play2/raw/main/",
    songs: [
{ file: "tamil_iragai_pole_clup_mix_tape.mp3", details: "Remix By dj jose", duration: 359 },
{ file: "Jorthaale wraith Vs Remix.m4a", details: "📀 Jorthaale (Wraith V Remix) (2021) / 🎙️ Asal Kolaar, ofRO / 🎼 Wraith V / 📝 Asal Kolaar", duration: 185 },
{ file: "vada vada Paiya mix.m4a", details: "💿 youtube Source NO1 AUDIO MIXER", duration: 290 }

]
  },

  {
    base: "https://raw.githubusercontent.com/atsuperman/O1/refs/heads/main/",
    songs: [

{ file: "Kuthu Fire- Vidya Vox.m4a", details: "📀 Kuthu Fire (2017) / 🎙️ Vidya Vox / 🎼 Shankar Tucker / 📝 Vidya Vox, Shankar Tucker", duration: 205 },
{ file: "Machi mannaru.m4a", details: "📀Dj Donz (1999) / 📁 80s remix", duration: 220 },
{ file: "Moodu- Brodha V.m4a", details: "📀 Moodu (2023) / 🎙️ Brodha V / 🎼 Brodha V / 📝 Brodha V", duration: 133 },
{ file: "Sundariye mix.m4a", details: "📀 DJ unknown (2013)", duration: 279 },
{ file: "vangonna echo extend mix.m4a", details: "📀 DJ unknown (2012)", duration: 222 },
{ file: "vazha thoppukulla mix.m4a", details: "📀 DJ unknown (2014)", duration: 253 },
{ file: "Thuppuran.m4a", details: "📀 Thuppuran (2022) / 🎙️ ADK, Lucky Lakmina, Abu Karim Ismail / 🎼 Pasan Liyanage / 📝 ADK, Lucky Lakmina, Pasan Liyanage", duration: 175 }

]
  }

];


// Build final songs array with full URL and duration
export const songs = [];
for (const repo of repos) {
  for (const s of repo.songs) {
    songs.push({
      file: s.file,
      url: repo.base + encodeURIComponent(s.file),
      details: s.details,
      duration: s.duration
    });
  }
}
